---
project:
  type: website
  output-dir: docs
website:
  navbar:
    title: "NCSU GeoForAll Lab SIMWE - NRCS"
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Reports"
        href: output/project_reports.qmd
      - text: "Notebooks"
        href: notebooks/index.qmd
      - text: "Presentations"
        href: presentations/index.qmd
      - text: "Publications"
        href: publications/index.qmd
      - text: "Data"
        href: data/index.qmd
      - text: "Scripts"
        href: scripts/index.qmd
      - text: "Tools"
        href: tools/index.qmd
    tools:
      - icon: github
        menu:
          - text: "Source Code"
            href: "https://github.com/ncsu-geoforall-lab/NRCS_SIMWE"
          - text: "Report an Issue"
            href: "https://github.com/ncsu-geoforall-lab/NRCS_SIMWE/issues"

execute:
  freeze: auto
format:
  html:
    theme: [pandoc, grass.scss]
    toc: true
    toc-title: Table of Contents
