---
jupyter: python3
author: Corey T. White
execute:
  eval: true
  freeze: auto
date-modified: today
format:
  html:
    toc: true
    code-tools: true
    code-copy: true
    code-fold: false
    mermaid:
      theme: forest
---

# [WIP] SSURGO Soil Data in GRASS

This notebook demonstrates how to import SSURGO soil data into GRASS using the `r.in.ssurgo` extension. The `r.in.ssurgo` tool can import both local SSURGO data and data from the Soil Data Access (SDA) web service. The imported data includes *soil areas*, *hydrologic groups*, *ksat maps*, and *mukey maps*, which can be used for hydrological modeling and analysis in GRASS.

The flowchart below (@fig_ssurgo_flowchart) illustrates the workflow for using SSURGO data in GRASS, including the tools and outputs that can be generated from the imported soil data. We will cover the following steps in this notebook:

```{mermaid}
%% label: fig_ssurgo_flowchart
%% echo: false
%% fig-cap: "(Draft) Flowchart of SSURGO SIMWE workflows"
flowchart TD
    A[r.in.ssurgo] --> B("Soils map vector")
    A[r.in.ssurgo] --> HG("Hydrologic group map")
    A[r.in.ssurgo] --> KSAT("Ksat maps rasters")
    A[r.in.ssurgo] --> E("MUKEY map raster")
    B --> F("Soil attributes in vector attribute table")
    G[r.curvenumber] --> H("Curve number map")
    HG --> G
    LC(NLCD land cover map) --> G
    ELEV[Elevation raster] --> W[r.watershed]
    W --> I("Flow direction")
    W --> J("Streams")
    W --> K("Basins")
    TC[r.timeofconcentration] --> TCR("Time of concentration")
    ELEV --> TC
    I --> TC
    J --> TC
    H --> R[r.runoff]
    I --> R
    TCR --> R
    R --> RD("Runoff depth")
    R --> RV("Runoff volume")
    R --> TP("Time to peak")
    R --> PD("Peak discharge raster")
    R --> URD("Upstream runoff depth")
    R --> URV("Upstream runoff volume")
    R --> UA("Upstream area")
    LC --> MC["r.manning"]
    MC --> MN("Manning's n map")
    ELEV --> RSA["r.slope.aspect"]
    RSA --> DX("dx")
    RSA --> DY("dy")
    ELEV --> SIMWE["r.sim.water"]
    DX --> SIMWE
    DY --> SIMWE
    MN --> SIMWE
    HG --> SIMWE
    KSAT --> SIMWE
    SIMWE --> DEPTH("Water depth raster")
    SIMWE --> DISCHARGE("Discharge raster")
```

## Objectives

1. Import SSURGO soil data into GRASS using `r.in.ssurgo`.
2. Visualize the imported soil maps, including soil areas, hydrologic groups, ksat maps, and mukey maps.
3. Calculate curve number using the imported hydrologic group map and a land cover map.
4. Calculate runoff depth and peak discharge using the curve number map, flow direction, and time of concentration.
5. Run a basic SIMWE simulation using the imported soil data and visualize the results.

```{python}
# | label: imports
# | echo: false
import os
import subprocess
import sys

# import numpy as np
import matplotlib.pyplot as plt
from pprint import pprint
from PIL import Image
import pandas as pd
import sqlite3
from IPython.display import IFrame
import numpy as np
import seaborn as sns
import pandas as pd

# Ask GRASS GIS where its Python packages are.
sys.path.append(
    subprocess.check_output(["grass", "--config", "python_path"], text=True).strip()
)

# Import the GRASS GIS packages we need.
import grass.script as gs

# Import GRASS Jupyter
import grass.jupyter as gj
from grass.tools import Tools
```

```{python}
# | label: init_session
# | echo: false
# | output: false
gisdb = os.path.join(os.getenv("HOME"), "grassdata")
site = "coweeta"
mapset = "ssurgo_demo"
session = gj.init(gisdb, site, "PERMANENT")
tools = Tools(session=session)
try:
    tools.g_mapset(mapset=mapset, flags="c")
except Exception as e:
    print(f"{e}")
```

Install the `r.in.ssurgo` extension if it is not already installed. This extension is available in the GRASS Addons repository and can be installed using `g.extension`. The source code for this extension is also available in the `tools/r.soildb/r.in.ssurgo` directory of this repository.

```{python}
# | label: install_extension
# | eval: false
# | echo: false

tools.g_extension(
    extension="r.in.ssurgo",
    url="../../../cwhite911/grass-addons/src/raster/r.in.ssurgo"
)

```

::: {.panel-tabset}

## Command Line

```sh
g.extension r.in.ssurgo
```

## Python (grass.tools)

```python
tools.g_extension(
    extension="r.in.ssurgo"
)
```
:::

Set the computational region to the elevation raster and create a relief raster for hillshading.

```{python}
# | label: set_region
region_text = tools.g_region(raster="elevation", flags="p").text
print(region_text)
```

Let's also create a relief raster for hillshading or soil maps.

```{python}
tools.r_relief(input="elevation", output="relief")
```

Import SSURGO data using `r.in.ssurgo`. Note that this will import the soil areas map, hydrologic group map, and ksat maps for low, regular, and high values. The `mukey` column is also imported as a raster with a categorical color scheme applied. The hydrologic group map also has a categorical color scheme applied.

::: {.panel-tabset}

## Local Import
```{python}
# | label: import_ssurgo_local
# | eval: false

results = tools.r_in_ssurgo(
    ssurgo_path="../data/gSSURGO_NC.zip",
    soils="soil_areas",
    hydgrp="hydgrp",
    ksat_l="ksat_l",
    ksat_r="ksat_r",
    ksat_h="ksat_h",
    mukey="mukey",
    hzdept_r=0,
    hzdepb_r=100,
    desgnmaster="A",
    nprocs=30
)

print(results)
```


## SDA Import
```{python}
# | label: import_ssurgo_sda
# | eval: false
tools.r_in_ssurgo(
    soils="soil_areas_sda",
    hydgrp="hydgrp_sda",
    ksat_l="ksat_l_sda",
    ksat_r="ksat_r_sda",
    ksat_h="ksat_h_sda",
    mukey="mukey_sda",
    hzdept_r=0,
    hzdepb_r=100,
    desgnmaster="A",
    nprocs=30
)
```

:::


```{python}
# | label: vector_maps
print(tools.g_list(type="vector", mapset=mapset).text)
```

```{python}
# | label: SDA soil attributes info
# | echo: false
json_data = tools.v_db_select(map="soil_areas_sda", format="json").json
df = pd.DataFrame(json_data["records"])
df.info()
```

```{python}
# | label: SDA soil attributes
# | echo: false
json_data = tools.v_db_select(map="soil_areas_sda", format="json").json
df = pd.DataFrame(json_data["records"])
df.head()
```

```{python}
# | label: local soil attributes
# | echo: false
json_data = tools.v_db_select(map="soil_areas", format="json").json
df = pd.DataFrame(json_data["records"])
df.info()
```

```{python}
# | label: list_rasters
print(tools.g_list(type="raster", mapset=mapset).text)
```

## MUKEY Map
```{python}
# | label: mukey
# | echo: false
# m = gj.Map(use_region=True)
# m.d_shade(shade="relief", color="mukey")
# m.d_vect(map="soil_areas", color="black", fillcolor="none", width=0.5)
# # m.d_legend(raster="mukey", title="MUKEY", flags="b")
# m.show()

# | label: mukey
m = gj.Map(use_region=True)
m.d_shade(shade="relief", color="mukey_sda")
m.d_vect(map="soil_areas_sda", color="black", fillcolor="none", width=0.5)
# m.d_legend(raster="mukey", title="MUKEY", flags="b")
m.show()
```

## Ksat Maps

### Regular
```{python}
# | label: ksat
# | layout-ncol: 3
# | echo: false
# | fig-cap: "Ksat maps for low, regular, and high values"
# | fig-subcap:
# |     - Low
# |     - Regular
# |     - High
# |     - Low - SDA
# |     - Regular - SDA
# |     - High - SDA


# m = gj.Map(use_region=True)
# m.d_shade(shade="relief", color="ksat_l")
# m.d_legend(raster="ksat_l", title="Ksat (mm/hr)", flags="db")
# m.show()

# m = gj.Map(use_region=True)
# m.d_shade(shade="relief", color="ksat_r")
# m.d_legend(raster="ksat_r", title="Ksat (mm/hr)", flags="db")
# m.show()

# m = gj.Map(use_region=True)
# m.d_shade(shade="relief", color="ksat_h")
# m.d_legend(raster="ksat_h", title="Ksat (mm/hr)", flags="db")
# m.show()

m = gj.Map(use_region=True)
m.d_shade(shade="relief", color="ksat_l_sda")
m.d_legend(raster="ksat_l_sda", title="Ksat (mm/hr)", flags="db")
m.show()

m = gj.Map(use_region=True)
m.d_shade(shade="relief", color="ksat_r_sda")
m.d_legend(raster="ksat_r_sda", title="Ksat (mm/hr)", flags="db")
m.show()

m = gj.Map(use_region=True)
m.d_shade(shade="relief", color="ksat_h_sda")
m.d_legend(raster="ksat_h_sda", title="Ksat (mm/hr)", flags="db")
m.show()
```

## Hydrologic Group

We can visualize the hydrologic group maps to compare the local and SDA imports. The hydrologic group map is a categorical raster with values of A, B, C, D, and A/D. The color scheme is applied using `r.colors` with the `hydgrp` color table.

```{python}
# | label: hydrologic_group_map
# | layout-ncol: 1
# | echo: false
# | fig-cap: "Hydrologic groups"

with gs.RegionManager(raster="hydgrp", s="s-50000", flags="a"):
    tools.g_region(raster="hydgrp_sda", flags="p")
    m = gj.Map(use_region=False)
    m.d_shade(shade="relief", color="hydgrp")
    m.d_legend(raster="hydgrp", flags="bn", at="0, 30, 1, 30")
    m.show()

    # m = gj.Map(use_region=False)
    # m.d_shade(shade="relief", color="hydgrp_sda")
    # m.d_legend(raster="hydgrp_sda", flags="bn")
    # m.show()
```


```{python}
# | label: hydrologic_group_map_comparison
# | echo: false
tools.r_mapcalc(
    expression="hydgrp_diff = hydgrp - hydgrp_sda",
)

m = gj.Map(use_region=True)
m.d_shade(shade="relief", color="hydgrp_diff")
m.d_legend(raster="hydgrp_diff", title="Difference", flags="b")
m.show()
```

## Curve Number

Install the `r.curvenumber` extension if it is not already installed. This extension is available in the GRASS Addons repository and can be installed using `g.extension`.

```python
# | label: install_curvenumber_text
# | eval: false
tools.g_extension(
    extension="r.curvenumber",
)
```

```{python}
# | label: install_curvenumber
# | eval: false
# | echo: false
tools.g_extension(
    extension="r.curvenumber",
    url="../../../cwhite911/grass-addons/src/raster/r.curvenumber"
)
```

```{python}
# | label: install_test_extensions
# | eval: false
# | echo: false
tmp_addon_test = [
    # "r.stream.basins",
    # "r.stream.distance",
    # "r.stream.order",
    # "r.stream.segment",
    # "r.stream.slope",
    # "r.stream.snap",
    # "r.stream.stats",
    # "r.stream.variables",
    # "r.stream.watersheds"
]
for addon in tmp_addon_test:
    try:
        tools.g_extension(
            extension=addon,
            url=f"../../../cwhite911/grass-addons/src/raster/{addon}"
        )
    except Exception as e:
        print(f"{e}")

```


To calculate the curve number, we need both a land cover map and a hydrologic soil group map. The land cover map is from the National Land Cover Database (NLCD) 2024 dataset, which was imported as a COG raster. The `landcover_source` parameter specifies that the land cover map is from the NLCD dataset, which allows the tool to use the appropriate lookup table for curve number values.

```{python}
#| label: import_landcover
#| eval: false
tools.r_import(
    output="nlcd_2024",
    input="<path_to_nlcd_cog>",
    extent="region",
    resolution="region",
)

```

NLCD 2024 land cover map:

```{python}
#| label: landcover_map
m = gj.Map(use_region=True)
m.d_shade(shade="relief", color="nlcd_2024")
# m.d_legend(raster="nlcd_2024", title="NLCD 2024", flags="b")
m.show()
```

Calculate the hydrolic curve number using the `r.curvenumber` extension, which requires both a land cover map and a hydrologic soil group map. The land cover map is from the National Land Cover Database (NLCD) 2024 dataset, which was imported as a COG raster. The `landcover_source` parameter specifies that the land cover map is from the NLCD dataset, which allows the tool to use the appropriate lookup table for curve number values.

```{python}
# | label: curvenumber_calc
tools.r_curvenumber(
    landcover="nlcd_2024",
    soil="hydgrp_sda",
    landcover_source="nlcd",
    output="curvenumber",
)
```

```{python}
#| label: curvenumber_map
m = gj.Map(use_region=True)
m.d_shade(shade="relief", color="curvenumber")
m.d_legend(raster="curvenumber", title="Curve Number", flags="b")
m.show()
```

Let's also run `r.runoff` to calculate runoff depth using the curve number method. This tool requires a precipitation raster, which we can create using `r.mapcalc` with a constant value for precipitation.

```{python}
# | label: install_toc_extension
# | eval: false
# | echo: false
tools.g_extension(
    extension="r.timeofconcentration",
    url="../../../cwhite911/grass-addons/src/raster/r.timeofconcentration",
)
tools.g_extension(
    extension="r.stream.distance",
    url="../../../cwhite911/grass-addons/src/raster/r.stream.distance",
)
```

```{python}
# | label: install_runoff_extension
# | eval: false
# | echo: false
tools.g_extension(
    extension="r.accumulate",
    url="../../../cwhite911/grass-addons/src/raster/r.accumulate",
)
tools.g_extension(
    extension="r.runoff", url="../../../cwhite911/grass-addons/src/raster/r.runoff"
)
```

We need the flow direction and stream maps to run `r.runoff` with time of concentration, which can be calculated using the `r.watershed` tool.

```{python}
#| label: watershed
tools.r_watershed(
    elevation="elevation",
    drainage="flow_direction",
    accumulation="accumulation",
    stream="stream",
    basin="basins",
    threshold=50000,
)
```

Let calculate the time of concentration using the `r.timeofconcentration` tool, which requires an elevation raster, flow direction raster, and stream raster as inputs. The output is a raster of time of concentration values in hours.

```{python}
# | label: time_of_concentration
tools.r_timeofconcentration(
    elevation="elevation",
    direction="flow_direction",
    stream="stream",
    time_concentration="time_concentration",
)
```


```{python}
# | label: extension_import_accumulate_runoff
# | echo: false
# | eval: false
tools.g_extension(
    extension="r.accumulate",
    url="../../../cwhite911/grass-addons/src/raster/r.accumulate",
)
tools.g_extension(
    extension="r.runoff", url="../../../cwhite911/grass-addons/src/raster/r.runoff"
)
```

```{python}
# | label: precipitation
tools.r_mapcalc(
    expression="rain = 50",  # 50 mm of precipitation
)

tools.r_runoff(
    rainfall="rain",
    direction="flow_direction",
    duration=24,  # hrs
    curvenumber="curvenumber",
    time_concentration="time_concentration",
    runoff_depth="runoff_depth",
    runoff_volume="runoff_volume",
    upstream_area="upstream_area",
    upstream_runoff_depth="upstream_runoff_depth",
    upstream_runoff_volume="upstream_runoff_volume",
    time_to_peak="time_to_peak",
    peak_discharge="peak_discharge"

)
```

Let's visualize the runoff depth and peak discharge maps.

```{python}
# | label: runoff_map
tools.r_colors(map="runoff_depth", color="water")
m = gj.Map(use_region=True)
m.d_shade(shade="relief", color="runoff_depth")
m.d_legend(raster="runoff_depth", title="Runoff Depth (mm)", flags="b")
m.show()
```

```{python}
# | label: peak_discharge_map
m = gj.Map(use_region=True)
m.d_shade(shade="relief", color="peak_discharge")
m.d_legend(raster="peak_discharge", title="Peak Discharge (m³/s)", flags="b")
m.show()
```


## Run model

Calcuate the slope and aspect from the elevation raster, which are required inputs for the `r.sim.water` tool.

```{python}
# | label: r_sim_water
# | eval: false
tools.r_slope_aspect(elevation="elevation", dx="dx", dy="dy")
tools.r_sim_water(elevation="elevation", depth="depth", discharge="discharge")
```


```{python}
# | label: depth_map
m = gj.Map(use_region=True)
m.d_rast(map="depth")
m.d_shade(shade="relief", color="depth")
m.show()
```

```{python}
# | label: discharge_map
m = gj.Map(use_region=True)
m.d_rast(map="discharge")
m.show()
```
