{
    "hash": "5b2158e3c927d187c8335b88fdde3bd3",
    "result": {
        "engine": "jupyter",
        "markdown": "---\njupyter: python3\nauthor: Corey T. White\nexecute:\n  eval: true\n  freeze: auto\ndate-modified: today\nformat:\n  html:\n    toc: true\n    code-tools: true\n    code-copy: true\n    code-fold: true\n    mermaid:\n      theme: forest\n    lightbox: true\ntitle: Study Area\n---\n\n\n\n# Clay Center, KS -- Soil-Informed Overland Flow Simulation\n\nOverland flow simulations typically apply a uniform rainfall rate across the landscape, treating every cell as if it sheds the same fraction of precipitation as runoff. In reality, soils vary: a sandy loam absorbs far more rain than a clay, so the water that actually runs off -- the *rainfall excess* -- differs from place to place. This notebook uses USDA SSURGO soil survey data to build a spatially varying rainfall-excess surface and feeds it into the SIMWE shallow-water model, then compares the result to a naive uniform-rainfall simulation.\n\n## Objectives\n\n1. Import SSURGO soil properties (hydrologic groups, saturated hydraulic conductivity) from the USDA Soil Data Access service.\n2. Derive a curve-number map by combining hydrologic soil groups with NLCD 2024 land cover, capturing how different soil--cover combinations partition rainfall into infiltration and runoff.\n3. Design a 100-year storm whose duration matches the watershed's time of concentration, ensuring peak runoff conditions.\n4. Convert SCS curve-number runoff depths into a spatially varying rainfall-excess rate (mm/hr) suitable for SIMWE.\n5. Run SIMWE twice -- once with soil-informed rainfall excess and once with uniform rainfall -- and compare the resulting flow-depth patterns.\n\n\n\n\nClay Center sits in the Republican River basin of north-central Kansas (39.400 N, 97.063 W), a region dominated by cultivated crops on deep loess-derived soils. Hydrologic soil groups here range from B (moderate infiltration) to D (very slow infiltration), making it a good test case for soil-informed runoff modeling. We use a GRASS mapset called `ssurgo_demo` for all imports and analysis.\n\n\n\n\n---\n\n### Computational Region\n\nWe align the computational region to the 10 m elevation raster and create a hillshade for cartographic context beneath the soil and runoff maps that follow.\n\n::: {#set_region .cell execution_count=3}\n``` {.python .cell-code}\nregion_text = tools.g_region(raster=\"elevation\", flags=\"pac\").text\nprint(region_text)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nprojection:      1 (UTM)\nzone:            14\ndatum:           wgs84\nellipsoid:       wgs84\nnorth:           4363578.81553571\nsouth:           4362417.81553571\nwest:            666092.80807312\neast:            667469.80807312\nnsres:           3\newres:           3\nrows:            387\ncols:            459\ncells:           177633\ncenter easting:  666781.308073\ncenter northing: 4362998.315536\n```\n:::\n:::\n\n\nLet's also create a relief raster for hillshading or soil maps.\n\n::: {#e61fb3a8 .cell execution_count=4}\n``` {.python .cell-code}\ntools.r_relief(input=\"elevation\", output=\"relief\")\n```\n:::\n\n\n## Importing SSURGO Soil Data\n\nThe first step toward spatially varying rainfall excess is obtaining soil properties. The USDA SSURGO database maps soil polygons (map-unit keys, or MUKEYs) and assigns each polygon laboratory-measured properties including hydrologic soil group (A through D) and saturated hydraulic conductivity (Ksat). We pull these directly from the Soil Data Access (SDA) web service using `r.in.ssurgo`, which rasterizes the polygons to match our computational region.\n\n::: {#import_ssurgo_sda .cell execution_count=5}\n``` {.python .cell-code}\ntools.r_in_ssurgo(\n    soils=\"soil_areas_sda\",\n    hydgrp=\"hydgrp_sda\",\n    ksat_l=\"ksat_l_sda\",\n    ksat_r=\"ksat_r_sda\",\n    ksat_h=\"ksat_h_sda\",\n    mukey=\"mukey_sda\",\n    hzdept_r=0,\n    hzdepb_r=100,\n    desgnmaster=\"A\",\n    nprocs=30\n)\n```\n:::\n\n\n## Visualize Imported Data\n\nBefore modeling, it is worth inspecting the imported layers to confirm spatial coverage and to build intuition about the soil landscape. The vector map `soil_areas_sda` carries the original SSURGO polygon attributes, while the rasterized layers (MUKEY, Ksat, hydrologic group) are what we use in subsequent calculations.\n\n::: {#cell-SDA-soil-attributes .cell execution_count=6}\n\n::: {#sda-soil-attributes .cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>cat</th>\n      <th>mukey</th>\n      <th>mukey_int</th>\n      <th>cokey</th>\n      <th>comppct_r</th>\n      <th>hydgrp</th>\n      <th>ksat_l</th>\n      <th>ksat_r</th>\n      <th>ksat_h</th>\n      <th>hsg</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1</td>\n      <td>1454645</td>\n      <td>1454645</td>\n      <td>26334409</td>\n      <td>85</td>\n      <td>B</td>\n      <td>15.228</td>\n      <td>32.399997</td>\n      <td>50.795997</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>2</td>\n      <td>1454645</td>\n      <td>1454645</td>\n      <td>26334409</td>\n      <td>85</td>\n      <td>B</td>\n      <td>15.228</td>\n      <td>32.399997</td>\n      <td>50.795997</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>3</td>\n      <td>1454645</td>\n      <td>1454645</td>\n      <td>26334409</td>\n      <td>85</td>\n      <td>B</td>\n      <td>15.228</td>\n      <td>32.399997</td>\n      <td>50.795997</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>4</td>\n      <td>1454645</td>\n      <td>1454645</td>\n      <td>26334409</td>\n      <td>85</td>\n      <td>B</td>\n      <td>15.228</td>\n      <td>32.399997</td>\n      <td>50.795997</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>5</td>\n      <td>1454645</td>\n      <td>1454645</td>\n      <td>26334409</td>\n      <td>85</td>\n      <td>B</td>\n      <td>15.228</td>\n      <td>32.399997</td>\n      <td>50.795997</td>\n      <td>2</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n### MUKEY Map\n\n::: {#cell-mukey .cell execution_count=7}\n\n::: {.cell-output .cell-output-display}\n![](ssurgo_clay_center_files/figure-html/mukey-output-1.png){#mukey}\n:::\n:::\n\n\n### Ksat Maps\n\n::: {#ksat .cell layout-ncol='3' execution_count=8}\n\n::: {.cell-output .cell-output-display}\n![Low](ssurgo_clay_center_files/figure-html/ksat-output-1.png){#ksat-1}\n:::\n\n::: {.cell-output .cell-output-display}\n![Regular](ssurgo_clay_center_files/figure-html/ksat-output-2.png){#ksat-2}\n:::\n\n::: {.cell-output .cell-output-display}\n![High](ssurgo_clay_center_files/figure-html/ksat-output-3.png){#ksat-3}\n:::\n\nKsat maps for low, regular, and high values\n:::\n\n\nKsat (saturated hydraulic conductivity) describes how quickly water moves through saturated soil. Higher values (blues) indicate coarser, more permeable soils; lower values (browns) indicate finer, less permeable soils. Although Ksat could be used directly as an infiltration input to SIMWE via the `infil` parameter, in this notebook we instead use the SCS curve-number method to account for infiltration. The curve-number approach integrates soil group, land cover, and antecedent moisture into a single runoff-depth estimate, which is better suited to event-based design-storm analysis. We retain the Ksat maps here for reference and potential future use with continuous-simulation approaches.\n\n### Hydrologic Soil Group\n\nHydrologic soil group is the key link between SSURGO data and the curve-number method. The USDA classifies soils into four groups based on their minimum infiltration rate: **A** (sand/gravel, high infiltration), **B** (moderate), **C** (slow), and **D** (clay, very slow). Dual-class soils like A/D behave as A when drained and D when undrained. The spatial pattern of these groups directly controls where runoff is generated in the curve-number calculation that follows.\n\n::: {#cell-hydrologic_group_map .cell layout-ncol='1' execution_count=9}\n\n::: {.cell-output .cell-output-display}\n![Hydrologic groups](ssurgo_clay_center_files/figure-html/hydrologic_group_map-output-1.png){#hydrologic_group_map}\n:::\n:::\n\n\n## From Soils to Runoff: The Curve Number\n\nThe SCS curve number (CN) translates the combination of soil group and land cover into a single index (0--100) that predicts how much rainfall becomes runoff. A high CN (e.g., 90 for impervious surfaces on group-D soil) means most rain runs off; a low CN (e.g., 30 for forest on group-A soil) means most rain infiltrates. By computing CN for every cell, we capture the spatial heterogeneity that a uniform-rainfall assumption ignores.\n\nTo calculate the curve number, we need both a land cover map and a hydrologic soil group map. The land cover map is from the National Land Cover Database (NLCD) 2024 dataset, which was imported as a COG raster.\n\n::: {#import_landcover .cell execution_count=10}\n``` {.python .cell-code}\ntools.r_import(\n    output=\"nlcd_2024\",\n    input=\"/home/coreywhite/Downloads/Annual_NLCD_LndCov_2024_CU_C1V1.cog.tif\",\n    extent=\"region\",\n    resolution=\"region\",\n)\n```\n:::\n\n\nNLCD 2024 land cover map:\n\n::: {#cell-landcover_map .cell layout-ncol='1' execution_count=11}\n\n::: {.cell-output .cell-output-display}\n![Land Cover](ssurgo_clay_center_files/figure-html/landcover_map-output-1.png){#landcover_map}\n:::\n\nLand cover map derived from the NLCD 2024 dataset.\n:::\n\n\nThe `r.curvenumber` extension cross-references each cell's NLCD land-cover class with its hydrologic soil group using standard NRCS lookup tables (TR-55).\n\n::: {#curvenumber_calc .cell execution_count=12}\n``` {.python .cell-code}\ntools.r_curvenumber(\n    landcover=\"nlcd_2024\",\n    soil=\"hydgrp_sda\",\n    landcover_source=\"nlcd\",\n    output=\"curvenumber\",\n)\n```\n:::\n\n\n::: {#cell-curvenumber_map .cell layout-ncol='1' execution_count=13}\n\n::: {.cell-output .cell-output-display}\n![Curve Number](ssurgo_clay_center_files/figure-html/curvenumber_map-output-1.png){#curvenumber_map}\n:::\n\nCurve number map derived from the NLCD 2024 dataset and hydrologic soil group map.\n:::\n\n\nThe CN map shows higher values over cultivated cropland on group-C/D soils and lower values where grassland overlies group-B soils. Next, we need the watershed's time of concentration to select an appropriate design-storm duration.\n\n## Watershed Delineation and Time of Concentration\n\nTo design a realistic storm event we need the watershed's *time of concentration* (Tc) -- the time it takes water to travel from the hydraulically most distant point to the outlet. When storm duration equals Tc, the entire watershed contributes runoff simultaneously, producing the peak discharge that engineering design must accommodate.\n\nWe first derive flow direction, streams, and sub-basins with `r.watershed`, then compute Tc with `r.timeofconcentration`.\n\n::: {#watershed .cell execution_count=14}\n``` {.python .cell-code}\ntools.r_watershed(\n    elevation=\"elevation\",\n    drainage=\"flow_direction\",\n    accumulation=\"accumulation\",\n    stream=\"stream\",\n    basin=\"basins\",\n    threshold=1000,\n)\n```\n:::\n\n\n::: {#watershed_map .cell layout-ncol='2' execution_count=15}\n\n::: {.cell-output .cell-output-display}\n![Flow Accumulation](ssurgo_clay_center_files/figure-html/watershed_map-output-1.png){#watershed_map-1}\n:::\n\n::: {.cell-output .cell-output-display}\n![Basins (1000 cell threshold)](ssurgo_clay_center_files/figure-html/watershed_map-output-2.png){#watershed_map-2}\n:::\n\nFlow accumulation and basins derived from the elevation raster using r.watershed with a 1000 cell threshold.\n:::\n\n\nWith flow direction and streams defined, we compute Tc for each cell using `r.timeofconcentration`. The result is a raster of travel times (in hours) from each cell to the nearest stream channel.\n\n::: {#time_of_concentration .cell execution_count=16}\n``` {.python .cell-code}\ntools.r_timeofconcentration(\n    elevation=\"elevation\",\n    direction=\"flow_direction\",\n    stream=\"stream\",\n    length_min=100,  # minimum length of flow path\n    tc=\"time_concentration\",\n)\n```\n:::\n\n\n::: {#cell-time_of_concentration_map .cell execution_count=17}\n``` {.python .cell-code}\nwith gs.RegionManager(raster=\"elevation\", s=\"s-250\", flags=\"a\"):\n    tools.r_colors(map=\"time_concentration\", color=\"byg\", flags=\"e\")\n    m = gj.Map(use_region=True, width=600)\n    m.d_shade(shade=\"relief\", color=\"time_concentration\")\n\n    m.d_legend(\n        raster=\"time_concentration\",\n        at=\"8, 12, 20, 80\",\n        title=\"Time of Concentration (hours)\",\n        font=\"Fira Sans Condensed Light\",\n        fontsize=14,\n        flags=\"s\",\n    )\n    m.d_barscale(\n        at=(68, 28),\n        font=\"Fira Sans Condensed Light\",\n        fontsize=10,\n        length=250,\n        unit=\"meters\",\n        width_scale=1,\n        bgcolor=\"none\",\n        # style=\"both_ticks\",\n        color=\"#1c1c1c\",\n        flags=\"n\",\n    )\n    m.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Time of Concentration](ssurgo_clay_center_files/figure-html/time_of_concentration_map-output-1.png){#time_of_concentration_map}\n:::\n\nTime of concentration derived from the elevation raster using r.timeofconcentration.\n:::\n\n\nSummary statistics for the Tc raster show the range of travel times across the watershed. The maximum Tc determines the design-storm duration.\n\n::: {#cell-time_of_concentration_stats .cell execution_count=18}\n\n::: {#time_of_concentration_stats .cell-output .cell-output-display}\n```{=html}\n<style type=\"text/css\">\n</style>\n<table id=\"T_decc6\">\n  <caption>Time of Concentration — Summary Statistics</caption>\n  <thead>\n    <tr>\n      <th id=\"T_decc6_level0_col0\" class=\"col_heading level0 col0\" >Statistic</th>\n      <th id=\"T_decc6_level0_col1\" class=\"col_heading level0 col1\" >Value</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td id=\"T_decc6_row0_col0\" class=\"data row0 col0\" >n</td>\n      <td id=\"T_decc6_row0_col1\" class=\"data row0 col1\" >6,695.000</td>\n    </tr>\n    <tr>\n      <td id=\"T_decc6_row1_col0\" class=\"data row1 col0\" >null_cells</td>\n      <td id=\"T_decc6_row1_col1\" class=\"data row1 col1\" >170,938.000</td>\n    </tr>\n    <tr>\n      <td id=\"T_decc6_row2_col0\" class=\"data row2 col0\" >cells</td>\n      <td id=\"T_decc6_row2_col1\" class=\"data row2 col1\" >177,633.000</td>\n    </tr>\n    <tr>\n      <td id=\"T_decc6_row3_col0\" class=\"data row3 col0\" >min</td>\n      <td id=\"T_decc6_row3_col1\" class=\"data row3 col1\" >0.034</td>\n    </tr>\n    <tr>\n      <td id=\"T_decc6_row4_col0\" class=\"data row4 col0\" >max</td>\n      <td id=\"T_decc6_row4_col1\" class=\"data row4 col1\" >0.901</td>\n    </tr>\n    <tr>\n      <td id=\"T_decc6_row5_col0\" class=\"data row5 col0\" >range</td>\n      <td id=\"T_decc6_row5_col1\" class=\"data row5 col1\" >0.867</td>\n    </tr>\n    <tr>\n      <td id=\"T_decc6_row6_col0\" class=\"data row6 col0\" >mean</td>\n      <td id=\"T_decc6_row6_col1\" class=\"data row6 col1\" >0.176</td>\n    </tr>\n    <tr>\n      <td id=\"T_decc6_row7_col0\" class=\"data row7 col0\" >mean_of_abs</td>\n      <td id=\"T_decc6_row7_col1\" class=\"data row7 col1\" >0.176</td>\n    </tr>\n    <tr>\n      <td id=\"T_decc6_row8_col0\" class=\"data row8 col0\" >stddev</td>\n      <td id=\"T_decc6_row8_col1\" class=\"data row8 col1\" >0.174</td>\n    </tr>\n    <tr>\n      <td id=\"T_decc6_row9_col0\" class=\"data row9 col0\" >variance</td>\n      <td id=\"T_decc6_row9_col1\" class=\"data row9 col1\" >0.030</td>\n    </tr>\n    <tr>\n      <td id=\"T_decc6_row10_col0\" class=\"data row10 col0\" >coeff_var</td>\n      <td id=\"T_decc6_row10_col1\" class=\"data row10 col1\" >99.243</td>\n    </tr>\n    <tr>\n      <td id=\"T_decc6_row11_col0\" class=\"data row11 col0\" >sum</td>\n      <td id=\"T_decc6_row11_col1\" class=\"data row11 col1\" >1,175.504</td>\n    </tr>\n    <tr>\n      <td id=\"T_decc6_row12_col0\" class=\"data row12 col0\" >first_quartile</td>\n      <td id=\"T_decc6_row12_col1\" class=\"data row12 col1\" >0.067</td>\n    </tr>\n    <tr>\n      <td id=\"T_decc6_row13_col0\" class=\"data row13 col0\" >median</td>\n      <td id=\"T_decc6_row13_col1\" class=\"data row13 col1\" >0.104</td>\n    </tr>\n    <tr>\n      <td id=\"T_decc6_row14_col0\" class=\"data row14 col0\" >third_quartile</td>\n      <td id=\"T_decc6_row14_col1\" class=\"data row14 col1\" >0.208</td>\n    </tr>\n    <tr>\n      <td id=\"T_decc6_row15_col0\" class=\"data row15 col0\" >percentile_percentile</td>\n      <td id=\"T_decc6_row15_col1\" class=\"data row15 col1\" >90.000</td>\n    </tr>\n    <tr>\n      <td id=\"T_decc6_row16_col0\" class=\"data row16 col0\" >percentile_value</td>\n      <td id=\"T_decc6_row16_col1\" class=\"data row16 col1\" >0.438</td>\n    </tr>\n  </tbody>\n</table>\n```\n:::\n:::\n\n\nThe maximum Tc across the watershed sets our design-storm duration. We now query NOAA Atlas 14 to find the rainfall intensity for a storm of that duration.\n\n## Designing the Storm: NOAA Atlas 14\n\nA design storm must answer two questions: *how intense?* and *for how long?* We have already determined the duration (equal to the watershed's maximum Tc). For the intensity, we use NOAA Atlas 14 precipitation-frequency estimates, which provide rainfall intensity--duration--frequency (IDF) curves for any point in the US. We extract the 100-year return-period intensity at the Tc duration -- representing a severe but plausible event -- to drive our simulation.\n\n\n\nWith the 100-year intensity at the Tc duration in hand, we compute total rainfall depth (intensity x duration) and create a uniform precipitation raster. This total depth is what the SCS curve-number equation needs to partition rainfall into infiltration and runoff.\n\n::: {#cell-tc_and_rfi .cell execution_count=20}\n``` {.python .cell-code}\ndf_tc_min = df_tc[[\"min\", \"mean\", \"max\"]].apply(\n    lambda x: round(x * 60, 2)\n)  # convert to minutes\nmax_tc = df_tc_min[\"max\"].max()\nprint(max_tc)\n\ndf_rf_intensity = pd.read_csv(io.StringIO(pfds_csv))\ndisplay(\n    df_rf_intensity.style.hide(axis=\"index\")\n    .set_caption(\"Rainfall Intensity — NOAA Atlas 14, Clay Center, NC\")\n    .format(\n        {\n            \"Value\": lambda v: f\"{v:,.3f}\"\n            if isinstance(v, (int, float, np.number))\n            else v\n        }\n    )\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n54.05\n```\n:::\n\n::: {#tc_and_rfi .cell-output .cell-output-display}\n```{=html}\n<style type=\"text/css\">\n</style>\n<table id=\"T_a1a12\">\n  <caption>Rainfall Intensity — NOAA Atlas 14, Clay Center, NC</caption>\n  <thead>\n    <tr>\n      <th id=\"T_a1a12_level0_col0\" class=\"col_heading level0 col0\" >duration</th>\n      <th id=\"T_a1a12_level0_col1\" class=\"col_heading level0 col1\" >1</th>\n      <th id=\"T_a1a12_level0_col2\" class=\"col_heading level0 col2\" >2</th>\n      <th id=\"T_a1a12_level0_col3\" class=\"col_heading level0 col3\" >5</th>\n      <th id=\"T_a1a12_level0_col4\" class=\"col_heading level0 col4\" >10</th>\n      <th id=\"T_a1a12_level0_col5\" class=\"col_heading level0 col5\" >25</th>\n      <th id=\"T_a1a12_level0_col6\" class=\"col_heading level0 col6\" >50</th>\n      <th id=\"T_a1a12_level0_col7\" class=\"col_heading level0 col7\" >100</th>\n      <th id=\"T_a1a12_level0_col8\" class=\"col_heading level0 col8\" >200</th>\n      <th id=\"T_a1a12_level0_col9\" class=\"col_heading level0 col9\" >500</th>\n      <th id=\"T_a1a12_level0_col10\" class=\"col_heading level0 col10\" >1000</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td id=\"T_a1a12_row0_col0\" class=\"data row0 col0\" >5-min</td>\n      <td id=\"T_a1a12_row0_col1\" class=\"data row0 col1\" >4.840000</td>\n      <td id=\"T_a1a12_row0_col2\" class=\"data row0 col2\" >5.720000</td>\n      <td id=\"T_a1a12_row0_col3\" class=\"data row0 col3\" >7.200000</td>\n      <td id=\"T_a1a12_row0_col4\" class=\"data row0 col4\" >8.460000</td>\n      <td id=\"T_a1a12_row0_col5\" class=\"data row0 col5\" >10.300000</td>\n      <td id=\"T_a1a12_row0_col6\" class=\"data row0 col6\" >11.700000</td>\n      <td id=\"T_a1a12_row0_col7\" class=\"data row0 col7\" >13.100000</td>\n      <td id=\"T_a1a12_row0_col8\" class=\"data row0 col8\" >14.700000</td>\n      <td id=\"T_a1a12_row0_col9\" class=\"data row0 col9\" >16.700000</td>\n      <td id=\"T_a1a12_row0_col10\" class=\"data row0 col10\" >18.300000</td>\n    </tr>\n    <tr>\n      <td id=\"T_a1a12_row1_col0\" class=\"data row1 col0\" >10-min</td>\n      <td id=\"T_a1a12_row1_col1\" class=\"data row1 col1\" >3.540000</td>\n      <td id=\"T_a1a12_row1_col2\" class=\"data row1 col2\" >4.190000</td>\n      <td id=\"T_a1a12_row1_col3\" class=\"data row1 col3\" >5.270000</td>\n      <td id=\"T_a1a12_row1_col4\" class=\"data row1 col4\" >6.200000</td>\n      <td id=\"T_a1a12_row1_col5\" class=\"data row1 col5\" >7.510000</td>\n      <td id=\"T_a1a12_row1_col6\" class=\"data row1 col6\" >8.550000</td>\n      <td id=\"T_a1a12_row1_col7\" class=\"data row1 col7\" >9.620000</td>\n      <td id=\"T_a1a12_row1_col8\" class=\"data row1 col8\" >10.700000</td>\n      <td id=\"T_a1a12_row1_col9\" class=\"data row1 col9\" >12.300000</td>\n      <td id=\"T_a1a12_row1_col10\" class=\"data row1 col10\" >13.400000</td>\n    </tr>\n    <tr>\n      <td id=\"T_a1a12_row2_col0\" class=\"data row2 col0\" >15-min</td>\n      <td id=\"T_a1a12_row2_col1\" class=\"data row2 col1\" >2.880000</td>\n      <td id=\"T_a1a12_row2_col2\" class=\"data row2 col2\" >3.400000</td>\n      <td id=\"T_a1a12_row2_col3\" class=\"data row2 col3\" >4.280000</td>\n      <td id=\"T_a1a12_row2_col4\" class=\"data row2 col4\" >5.040000</td>\n      <td id=\"T_a1a12_row2_col5\" class=\"data row2 col5\" >6.100000</td>\n      <td id=\"T_a1a12_row2_col6\" class=\"data row2 col6\" >6.950000</td>\n      <td id=\"T_a1a12_row2_col7\" class=\"data row2 col7\" >7.820000</td>\n      <td id=\"T_a1a12_row2_col8\" class=\"data row2 col8\" >8.730000</td>\n      <td id=\"T_a1a12_row2_col9\" class=\"data row2 col9\" >9.960000</td>\n      <td id=\"T_a1a12_row2_col10\" class=\"data row2 col10\" >10.900000</td>\n    </tr>\n    <tr>\n      <td id=\"T_a1a12_row3_col0\" class=\"data row3 col0\" >30-min</td>\n      <td id=\"T_a1a12_row3_col1\" class=\"data row3 col1\" >2.050000</td>\n      <td id=\"T_a1a12_row3_col2\" class=\"data row3 col2\" >2.420000</td>\n      <td id=\"T_a1a12_row3_col3\" class=\"data row3 col3\" >3.050000</td>\n      <td id=\"T_a1a12_row3_col4\" class=\"data row3 col4\" >3.590000</td>\n      <td id=\"T_a1a12_row3_col5\" class=\"data row3 col5\" >4.360000</td>\n      <td id=\"T_a1a12_row3_col6\" class=\"data row3 col6\" >4.980000</td>\n      <td id=\"T_a1a12_row3_col7\" class=\"data row3 col7\" >5.610000</td>\n      <td id=\"T_a1a12_row3_col8\" class=\"data row3 col8\" >6.270000</td>\n      <td id=\"T_a1a12_row3_col9\" class=\"data row3 col9\" >7.170000</td>\n      <td id=\"T_a1a12_row3_col10\" class=\"data row3 col10\" >7.870000</td>\n    </tr>\n    <tr>\n      <td id=\"T_a1a12_row4_col0\" class=\"data row4 col0\" >60-min</td>\n      <td id=\"T_a1a12_row4_col1\" class=\"data row4 col1\" >1.330000</td>\n      <td id=\"T_a1a12_row4_col2\" class=\"data row4 col2\" >1.570000</td>\n      <td id=\"T_a1a12_row4_col3\" class=\"data row4 col3\" >1.970000</td>\n      <td id=\"T_a1a12_row4_col4\" class=\"data row4 col4\" >2.330000</td>\n      <td id=\"T_a1a12_row4_col5\" class=\"data row4 col5\" >2.850000</td>\n      <td id=\"T_a1a12_row4_col6\" class=\"data row4 col6\" >3.280000</td>\n      <td id=\"T_a1a12_row4_col7\" class=\"data row4 col7\" >3.730000</td>\n      <td id=\"T_a1a12_row4_col8\" class=\"data row4 col8\" >4.210000</td>\n      <td id=\"T_a1a12_row4_col9\" class=\"data row4 col9\" >4.880000</td>\n      <td id=\"T_a1a12_row4_col10\" class=\"data row4 col10\" >5.400000</td>\n    </tr>\n    <tr>\n      <td id=\"T_a1a12_row5_col0\" class=\"data row5 col0\" >2-hr</td>\n      <td id=\"T_a1a12_row5_col1\" class=\"data row5 col1\" >0.818000</td>\n      <td id=\"T_a1a12_row5_col2\" class=\"data row5 col2\" >0.960000</td>\n      <td id=\"T_a1a12_row5_col3\" class=\"data row5 col3\" >1.210000</td>\n      <td id=\"T_a1a12_row5_col4\" class=\"data row5 col4\" >1.430000</td>\n      <td id=\"T_a1a12_row5_col5\" class=\"data row5 col5\" >1.760000</td>\n      <td id=\"T_a1a12_row5_col6\" class=\"data row5 col6\" >2.040000</td>\n      <td id=\"T_a1a12_row5_col7\" class=\"data row5 col7\" >2.330000</td>\n      <td id=\"T_a1a12_row5_col8\" class=\"data row5 col8\" >2.640000</td>\n      <td id=\"T_a1a12_row5_col9\" class=\"data row5 col9\" >3.080000</td>\n      <td id=\"T_a1a12_row5_col10\" class=\"data row5 col10\" >3.440000</td>\n    </tr>\n    <tr>\n      <td id=\"T_a1a12_row6_col0\" class=\"data row6 col0\" >3-hr</td>\n      <td id=\"T_a1a12_row6_col1\" class=\"data row6 col1\" >0.605000</td>\n      <td id=\"T_a1a12_row6_col2\" class=\"data row6 col2\" >0.708000</td>\n      <td id=\"T_a1a12_row6_col3\" class=\"data row6 col3\" >0.892000</td>\n      <td id=\"T_a1a12_row6_col4\" class=\"data row6 col4\" >1.060000</td>\n      <td id=\"T_a1a12_row6_col5\" class=\"data row6 col5\" >1.310000</td>\n      <td id=\"T_a1a12_row6_col6\" class=\"data row6 col6\" >1.520000</td>\n      <td id=\"T_a1a12_row6_col7\" class=\"data row6 col7\" >1.750000</td>\n      <td id=\"T_a1a12_row6_col8\" class=\"data row6 col8\" >1.990000</td>\n      <td id=\"T_a1a12_row6_col9\" class=\"data row6 col9\" >2.340000</td>\n      <td id=\"T_a1a12_row6_col10\" class=\"data row6 col10\" >2.620000</td>\n    </tr>\n    <tr>\n      <td id=\"T_a1a12_row7_col0\" class=\"data row7 col0\" >6-hr</td>\n      <td id=\"T_a1a12_row7_col1\" class=\"data row7 col1\" >0.355000</td>\n      <td id=\"T_a1a12_row7_col2\" class=\"data row7 col2\" >0.415000</td>\n      <td id=\"T_a1a12_row7_col3\" class=\"data row7 col3\" >0.523000</td>\n      <td id=\"T_a1a12_row7_col4\" class=\"data row7 col4\" >0.622000</td>\n      <td id=\"T_a1a12_row7_col5\" class=\"data row7 col5\" >0.771000</td>\n      <td id=\"T_a1a12_row7_col6\" class=\"data row7 col6\" >0.896000</td>\n      <td id=\"T_a1a12_row7_col7\" class=\"data row7 col7\" >1.030000</td>\n      <td id=\"T_a1a12_row7_col8\" class=\"data row7 col8\" >1.170000</td>\n      <td id=\"T_a1a12_row7_col9\" class=\"data row7 col9\" >1.380000</td>\n      <td id=\"T_a1a12_row7_col10\" class=\"data row7 col10\" >1.550000</td>\n    </tr>\n    <tr>\n      <td id=\"T_a1a12_row8_col0\" class=\"data row8 col0\" >12-hr</td>\n      <td id=\"T_a1a12_row8_col1\" class=\"data row8 col1\" >0.202000</td>\n      <td id=\"T_a1a12_row8_col2\" class=\"data row8 col2\" >0.237000</td>\n      <td id=\"T_a1a12_row8_col3\" class=\"data row8 col3\" >0.299000</td>\n      <td id=\"T_a1a12_row8_col4\" class=\"data row8 col4\" >0.355000</td>\n      <td id=\"T_a1a12_row8_col5\" class=\"data row8 col5\" >0.436000</td>\n      <td id=\"T_a1a12_row8_col6\" class=\"data row8 col6\" >0.504000</td>\n      <td id=\"T_a1a12_row8_col7\" class=\"data row8 col7\" >0.575000</td>\n      <td id=\"T_a1a12_row8_col8\" class=\"data row8 col8\" >0.651000</td>\n      <td id=\"T_a1a12_row8_col9\" class=\"data row8 col9\" >0.757000</td>\n      <td id=\"T_a1a12_row8_col10\" class=\"data row8 col10\" >0.843000</td>\n    </tr>\n    <tr>\n      <td id=\"T_a1a12_row9_col0\" class=\"data row9 col0\" >24-hr</td>\n      <td id=\"T_a1a12_row9_col1\" class=\"data row9 col1\" >0.115000</td>\n      <td id=\"T_a1a12_row9_col2\" class=\"data row9 col2\" >0.135000</td>\n      <td id=\"T_a1a12_row9_col3\" class=\"data row9 col3\" >0.169000</td>\n      <td id=\"T_a1a12_row9_col4\" class=\"data row9 col4\" >0.199000</td>\n      <td id=\"T_a1a12_row9_col5\" class=\"data row9 col5\" >0.242000</td>\n      <td id=\"T_a1a12_row9_col6\" class=\"data row9 col6\" >0.278000</td>\n      <td id=\"T_a1a12_row9_col7\" class=\"data row9 col7\" >0.314000</td>\n      <td id=\"T_a1a12_row9_col8\" class=\"data row9 col8\" >0.353000</td>\n      <td id=\"T_a1a12_row9_col9\" class=\"data row9 col9\" >0.406000</td>\n      <td id=\"T_a1a12_row9_col10\" class=\"data row9 col10\" >0.449000</td>\n    </tr>\n    <tr>\n      <td id=\"T_a1a12_row10_col0\" class=\"data row10 col0\" >2-day</td>\n      <td id=\"T_a1a12_row10_col1\" class=\"data row10 col1\" >0.065000</td>\n      <td id=\"T_a1a12_row10_col2\" class=\"data row10 col2\" >0.076000</td>\n      <td id=\"T_a1a12_row10_col3\" class=\"data row10 col3\" >0.094000</td>\n      <td id=\"T_a1a12_row10_col4\" class=\"data row10 col4\" >0.109000</td>\n      <td id=\"T_a1a12_row10_col5\" class=\"data row10 col5\" >0.132000</td>\n      <td id=\"T_a1a12_row10_col6\" class=\"data row10 col6\" >0.150000</td>\n      <td id=\"T_a1a12_row10_col7\" class=\"data row10 col7\" >0.170000</td>\n      <td id=\"T_a1a12_row10_col8\" class=\"data row10 col8\" >0.190000</td>\n      <td id=\"T_a1a12_row10_col9\" class=\"data row10 col9\" >0.218000</td>\n      <td id=\"T_a1a12_row10_col10\" class=\"data row10 col10\" >0.240000</td>\n    </tr>\n    <tr>\n      <td id=\"T_a1a12_row11_col0\" class=\"data row11 col0\" >3-day</td>\n      <td id=\"T_a1a12_row11_col1\" class=\"data row11 col1\" >0.047000</td>\n      <td id=\"T_a1a12_row11_col2\" class=\"data row11 col2\" >0.054000</td>\n      <td id=\"T_a1a12_row11_col3\" class=\"data row11 col3\" >0.067000</td>\n      <td id=\"T_a1a12_row11_col4\" class=\"data row11 col4\" >0.078000</td>\n      <td id=\"T_a1a12_row11_col5\" class=\"data row11 col5\" >0.094000</td>\n      <td id=\"T_a1a12_row11_col6\" class=\"data row11 col6\" >0.107000</td>\n      <td id=\"T_a1a12_row11_col7\" class=\"data row11 col7\" >0.120000</td>\n      <td id=\"T_a1a12_row11_col8\" class=\"data row11 col8\" >0.134000</td>\n      <td id=\"T_a1a12_row11_col9\" class=\"data row11 col9\" >0.154000</td>\n      <td id=\"T_a1a12_row11_col10\" class=\"data row11 col10\" >0.169000</td>\n    </tr>\n    <tr>\n      <td id=\"T_a1a12_row12_col0\" class=\"data row12 col0\" >4-day</td>\n      <td id=\"T_a1a12_row12_col1\" class=\"data row12 col1\" >0.038000</td>\n      <td id=\"T_a1a12_row12_col2\" class=\"data row12 col2\" >0.043000</td>\n      <td id=\"T_a1a12_row12_col3\" class=\"data row12 col3\" >0.053000</td>\n      <td id=\"T_a1a12_row12_col4\" class=\"data row12 col4\" >0.062000</td>\n      <td id=\"T_a1a12_row12_col5\" class=\"data row12 col5\" >0.074000</td>\n      <td id=\"T_a1a12_row12_col6\" class=\"data row12 col6\" >0.084000</td>\n      <td id=\"T_a1a12_row12_col7\" class=\"data row12 col7\" >0.095000</td>\n      <td id=\"T_a1a12_row12_col8\" class=\"data row12 col8\" >0.106000</td>\n      <td id=\"T_a1a12_row12_col9\" class=\"data row12 col9\" >0.120000</td>\n      <td id=\"T_a1a12_row12_col10\" class=\"data row12 col10\" >0.132000</td>\n    </tr>\n    <tr>\n      <td id=\"T_a1a12_row13_col0\" class=\"data row13 col0\" >7-day</td>\n      <td id=\"T_a1a12_row13_col1\" class=\"data row13 col1\" >0.025000</td>\n      <td id=\"T_a1a12_row13_col2\" class=\"data row13 col2\" >0.029000</td>\n      <td id=\"T_a1a12_row13_col3\" class=\"data row13 col3\" >0.035000</td>\n      <td id=\"T_a1a12_row13_col4\" class=\"data row13 col4\" >0.040000</td>\n      <td id=\"T_a1a12_row13_col5\" class=\"data row13 col5\" >0.048000</td>\n      <td id=\"T_a1a12_row13_col6\" class=\"data row13 col6\" >0.054000</td>\n      <td id=\"T_a1a12_row13_col7\" class=\"data row13 col7\" >0.060000</td>\n      <td id=\"T_a1a12_row13_col8\" class=\"data row13 col8\" >0.067000</td>\n      <td id=\"T_a1a12_row13_col9\" class=\"data row13 col9\" >0.076000</td>\n      <td id=\"T_a1a12_row13_col10\" class=\"data row13 col10\" >0.083000</td>\n    </tr>\n    <tr>\n      <td id=\"T_a1a12_row14_col0\" class=\"data row14 col0\" >10-day</td>\n      <td id=\"T_a1a12_row14_col1\" class=\"data row14 col1\" >0.020000</td>\n      <td id=\"T_a1a12_row14_col2\" class=\"data row14 col2\" >0.023000</td>\n      <td id=\"T_a1a12_row14_col3\" class=\"data row14 col3\" >0.028000</td>\n      <td id=\"T_a1a12_row14_col4\" class=\"data row14 col4\" >0.032000</td>\n      <td id=\"T_a1a12_row14_col5\" class=\"data row14 col5\" >0.038000</td>\n      <td id=\"T_a1a12_row14_col6\" class=\"data row14 col6\" >0.042000</td>\n      <td id=\"T_a1a12_row14_col7\" class=\"data row14 col7\" >0.047000</td>\n      <td id=\"T_a1a12_row14_col8\" class=\"data row14 col8\" >0.052000</td>\n      <td id=\"T_a1a12_row14_col9\" class=\"data row14 col9\" >0.059000</td>\n      <td id=\"T_a1a12_row14_col10\" class=\"data row14 col10\" >0.064000</td>\n    </tr>\n    <tr>\n      <td id=\"T_a1a12_row15_col0\" class=\"data row15 col0\" >20-day</td>\n      <td id=\"T_a1a12_row15_col1\" class=\"data row15 col1\" >0.014000</td>\n      <td id=\"T_a1a12_row15_col2\" class=\"data row15 col2\" >0.016000</td>\n      <td id=\"T_a1a12_row15_col3\" class=\"data row15 col3\" >0.019000</td>\n      <td id=\"T_a1a12_row15_col4\" class=\"data row15 col4\" >0.021000</td>\n      <td id=\"T_a1a12_row15_col5\" class=\"data row15 col5\" >0.025000</td>\n      <td id=\"T_a1a12_row15_col6\" class=\"data row15 col6\" >0.028000</td>\n      <td id=\"T_a1a12_row15_col7\" class=\"data row15 col7\" >0.031000</td>\n      <td id=\"T_a1a12_row15_col8\" class=\"data row15 col8\" >0.034000</td>\n      <td id=\"T_a1a12_row15_col9\" class=\"data row15 col9\" >0.038000</td>\n      <td id=\"T_a1a12_row15_col10\" class=\"data row15 col10\" >0.041000</td>\n    </tr>\n    <tr>\n      <td id=\"T_a1a12_row16_col0\" class=\"data row16 col0\" >30-day</td>\n      <td id=\"T_a1a12_row16_col1\" class=\"data row16 col1\" >0.011000</td>\n      <td id=\"T_a1a12_row16_col2\" class=\"data row16 col2\" >0.013000</td>\n      <td id=\"T_a1a12_row16_col3\" class=\"data row16 col3\" >0.015000</td>\n      <td id=\"T_a1a12_row16_col4\" class=\"data row16 col4\" >0.017000</td>\n      <td id=\"T_a1a12_row16_col5\" class=\"data row16 col5\" >0.020000</td>\n      <td id=\"T_a1a12_row16_col6\" class=\"data row16 col6\" >0.022000</td>\n      <td id=\"T_a1a12_row16_col7\" class=\"data row16 col7\" >0.024000</td>\n      <td id=\"T_a1a12_row16_col8\" class=\"data row16 col8\" >0.027000</td>\n      <td id=\"T_a1a12_row16_col9\" class=\"data row16 col9\" >0.029000</td>\n      <td id=\"T_a1a12_row16_col10\" class=\"data row16 col10\" >0.032000</td>\n    </tr>\n    <tr>\n      <td id=\"T_a1a12_row17_col0\" class=\"data row17 col0\" >45-day</td>\n      <td id=\"T_a1a12_row17_col1\" class=\"data row17 col1\" >0.009000</td>\n      <td id=\"T_a1a12_row17_col2\" class=\"data row17 col2\" >0.010000</td>\n      <td id=\"T_a1a12_row17_col3\" class=\"data row17 col3\" >0.012000</td>\n      <td id=\"T_a1a12_row17_col4\" class=\"data row17 col4\" >0.014000</td>\n      <td id=\"T_a1a12_row17_col5\" class=\"data row17 col5\" >0.016000</td>\n      <td id=\"T_a1a12_row17_col6\" class=\"data row17 col6\" >0.018000</td>\n      <td id=\"T_a1a12_row17_col7\" class=\"data row17 col7\" >0.019000</td>\n      <td id=\"T_a1a12_row17_col8\" class=\"data row17 col8\" >0.021000</td>\n      <td id=\"T_a1a12_row17_col9\" class=\"data row17 col9\" >0.023000</td>\n      <td id=\"T_a1a12_row17_col10\" class=\"data row17 col10\" >0.024000</td>\n    </tr>\n    <tr>\n      <td id=\"T_a1a12_row18_col0\" class=\"data row18 col0\" >60-day</td>\n      <td id=\"T_a1a12_row18_col1\" class=\"data row18 col1\" >0.008000</td>\n      <td id=\"T_a1a12_row18_col2\" class=\"data row18 col2\" >0.009000</td>\n      <td id=\"T_a1a12_row18_col3\" class=\"data row18 col3\" >0.011000</td>\n      <td id=\"T_a1a12_row18_col4\" class=\"data row18 col4\" >0.012000</td>\n      <td id=\"T_a1a12_row18_col5\" class=\"data row18 col5\" >0.014000</td>\n      <td id=\"T_a1a12_row18_col6\" class=\"data row18 col6\" >0.015000</td>\n      <td id=\"T_a1a12_row18_col7\" class=\"data row18 col7\" >0.016000</td>\n      <td id=\"T_a1a12_row18_col8\" class=\"data row18 col8\" >0.017000</td>\n      <td id=\"T_a1a12_row18_col9\" class=\"data row18 col9\" >0.019000</td>\n      <td id=\"T_a1a12_row18_col10\" class=\"data row18 col10\" >0.020000</td>\n    </tr>\n  </tbody>\n</table>\n```\n:::\n:::\n\n\n::: {#rainfall_intensity_figure .cell execution_count=21}\n\n::: {.cell-output .cell-output-display}\n![NOAA Atlas 14 rainfall intensity by storm duration for Coweeta, NC, with the maximum time of concentration marked.](ssurgo_clay_center_files/figure-html/rainfall_intensity_figure-output-1.png){#rainfall_intensity_figure-1 width=927 height=539}\n:::\n\n::: {#rainfall_intensity_figure-2 .cell-output .cell-output-display}\n```{=html}\n<style type=\"text/css\">\n</style>\n<table id=\"T_1854a\">\n  <caption>Interpolated rainfall intensity at maximum time of concentration</caption>\n  <thead>\n    <tr>\n      <th id=\"T_1854a_level0_col0\" class=\"col_heading level0 col0\" >return_period</th>\n      <th id=\"T_1854a_level0_col1\" class=\"col_heading level0 col1\" >max_tc_min</th>\n      <th id=\"T_1854a_level0_col2\" class=\"col_heading level0 col2\" >intensity_in_hr</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td id=\"T_1854a_row0_col0\" class=\"data row0 col0\" >100</td>\n      <td id=\"T_1854a_row0_col1\" class=\"data row0 col1\" >54.050000</td>\n      <td id=\"T_1854a_row0_col2\" class=\"data row0 col2\" >4.010000</td>\n    </tr>\n  </tbody>\n</table>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n100-year storm intensity at max Tc (54.05 min): 4.01 in/hr\n```\n:::\n:::\n\n\n::: {#precipitation_mm .cell execution_count=22}\n``` {.python .cell-code}\nduration_min = round(max_tc, 2)\nintensity_in_hr =rain_inches_per_hour\nintensity_mm_hr = intensity_in_hr * 25.4\n\nduration_hr = duration_min / 60.0\nrain_mm = intensity_mm_hr * duration_hr\n\nprint(f\"Storm duration: {duration_min:.4f} min\")\nprint(f\"Storm duration: {duration_hr:.4f} hr\")\nprint(f\"Rainfall intensity: {intensity_in_hr:.3f} in/hr\")\nprint(f\"Rainfall intensity: {intensity_mm_hr:.3f} mm/hr\")\nprint(f\"Rain depth: {rain_mm:.3f} mm\")\ntools.r_mapcalc(\n    expression=f\"rain = {rain_mm}\",  # mm of precipitation\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nStorm duration: 54.0500 min\nStorm duration: 0.9008 hr\nRainfall intensity: 4.013 in/hr\nRainfall intensity: 101.937 mm/hr\nRain depth: 91.828 mm\n```\n:::\n:::\n\n\n::: {#runoff_calculation .cell execution_count=23}\n``` {.python .cell-code}\n# tools.g_extension(extension=\"r.runoff\", url=\"../../../cwhite911/grass-addons/src/raster/r.runoff\")\n# Make sure you have the following GRASS addons installed\n# - r.accumulate\n# - r.runoff\n\ntools.r_runoff(\n    rainfall=\"rain\",\n    direction=\"flow_direction\",\n    duration=duration_hr,  # hours\n    curvenumber=\"curvenumber\",\n    time_concentration=\"time_concentration\",\n    runoff_depth=\"runoff_depth\",\n    runoff_volume=\"runoff_volume\",\n    upstream_area=\"upstream_area\",\n    upstream_runoff_depth=\"upstream_runoff_depth\",\n    upstream_runoff_volume=\"upstream_runoff_volume\",\n    time_to_peak=\"time_to_peak\",\n    peak_discharge=\"peak_discharge\",\n)\n```\n:::\n\n\nThe runoff depth map shows how much water (mm) runs off each cell after accounting for soil infiltration via the curve number. This is the spatially varying quantity we will convert to rainfall excess for SIMWE.\n\n::: {#cell-runoff_map .cell layout-ncol='1' execution_count=24}\n\n::: {.cell-output .cell-output-display}\n![Derived runoff depth (mm)](ssurgo_clay_center_files/figure-html/runoff_map-output-1.png){#runoff_map}\n:::\n\nRunoff Depth Map.\n:::\n\n\nThe `r.runoff` tool also produces peak discharge (m^3^/s) and time-to-peak (hours) rasters, which characterize the hydrologic response at each point in the watershed.\n\n::: {#peak_discharge_map .cell layout-ncol='2' execution_count=25}\n\n::: {.cell-output .cell-output-display}\n![Peak Discharge (m³/s)](ssurgo_clay_center_files/figure-html/peak_discharge_map-output-1.png){#peak_discharge_map-1}\n:::\n\n::: {.cell-output .cell-output-display}\n![Time to Peak (hours)](ssurgo_clay_center_files/figure-html/peak_discharge_map-output-2.png){#peak_discharge_map-2}\n:::\n\nDischarge\n:::\n\n\n## Overland Flow Simulation (SIMWE)\n\nSIMWE (`r.sim.water`) solves the shallow-water equations using a path-sampling method. It requires two spatially distributed inputs: a rainfall rate for each cell (the `rain` parameter, in mm/hr) and a surface-roughness coefficient (Manning's n). We prepare both below.\n\n### Surface Roughness: Manning's n\n\nWe derive Manning's n from the NLCD 2024 land-cover map using the lookup table from Kalyanapu et al. (2009), which assigns higher roughness to forested and wetland areas and lower values to developed and barren surfaces.\n\n::: {#mannings_n .cell execution_count=26}\n``` {.python .cell-code}\ntools.r_manning(\n    input=\"nlcd_2024\",\n    output=\"mannings_n\",\n    landcover=\"nlcd\",\n    source=\"kalyanapu\",\n    seed=42,\n)\n```\n:::\n\n\n::: {#cell-r_manning_map .cell layout-ncol='1' execution_count=27}\n\n::: {.cell-output .cell-output-display}\n![Manning's n](ssurgo_clay_center_files/figure-html/r_manning_map-output-1.png){#r_manning_map}\n:::\n\nManning's n map derived from the NLCD 2024 land cover map using the r.manning tool with the Kalyanapu et al. (2009) lookup table.\n:::\n\n\n### Converting Runoff Depth to Rainfall Excess\n\nThe SCS curve-number method gives us **runoff depth** (mm) -- the total depth of water that runs off each cell over the entire storm. SIMWE, however, needs an instantaneous **rainfall-excess rate** (mm/hr). To convert:\n\n$$\\text{rainfall excess (mm/hr)} = \\frac{\\text{runoff depth (mm)}}{\\text{storm duration (hr)}}$$\n\nOur design storm lasts for the watershed Tc of approximately 54 minutes (54/60 = 0.9 hours). Dividing the per-cell runoff depth by 0.9 hours yields the average rainfall-excess rate over the storm. This spatially varying raster replaces the uniform `rain_value` in the soil-informed simulation.\n\n::: {#rainfall_excess_calc .cell execution_count=28}\n``` {.python .cell-code}\ntools.r_mapcalc(\n    expression=f\"rainfall_excess = runoff_depth / 0.9\",\n)\n```\n:::\n\n\n::: {#cell-rainfall_excess_map .cell execution_count=29}\n``` {.python .cell-code}\nwith gs.RegionManager(raster=\"rainfall_excess\", s=\"s-250\", flags=\"a\"):\n    tools.r_colors(map=\"rainfall_excess\", color=\"water\", flags=\"e\")\n    m = gj.Map(use_region=True, width=600)\n    m.d_shade(shade=\"relief\", color=\"rainfall_excess\")\n    m.d_legend(\n        raster=\"rainfall_excess\",\n        at=\"8, 12, 20, 80\",\n        title=\"Rainfall Excess (mm/hr)\",\n        font=\"Fira Sans Condensed Light\",\n        fontsize=16,\n        flags=\"s\",\n    )\n    m.d_barscale(\n        at=(67, 25),\n        font=\"Fira Sans Condensed Light\",\n        fontsize=12,\n        length=250,\n        unit=\"meters\",\n        width_scale=1,\n        bgcolor=\"none\",\n        # style=\"both_ticks\",\n        color=\"#ffffff\",\n        flags=\"n\",\n    )\n    m.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ssurgo_clay_center_files/figure-html/rainfall_excess_map-output-1.png){#rainfall_excess_map}\n:::\n:::\n\n\n### Simulation A: Soil-Informed Rainfall Excess\n\nWe now run SIMWE for the full 54-minute design storm using the spatially varying `rainfall_excess` raster. Each cell receives only the rainfall that its soil--cover combination cannot absorb, so areas with high curve numbers (clay soils, cropland) generate more runoff than areas with low curve numbers (grassland on loamy soil). Manning's n from NLCD controls surface roughness.\n\nNote: the `infil` parameter (Ksat-based infiltration of flowing water) is available but intentionally left disabled. We have already accounted for infiltration through the curve-number rainfall excess. Enabling `infil` would double-count infiltration losses.\n\n::: {#r_sim_water .cell execution_count=30}\n``` {.python .cell-code}\n# 100yr storm running for 54.05 min with soil informed\n# Rainfall excess\nduration_min = 54.05\ntools.r_slope_aspect(elevation=\"elevation\", dx=\"dx\", dy=\"dy\")\ntools.r_sim_water(\n    elevation=\"elevation\",\n    depth=\"rx_100yr_depth\",\n    discharge=\"rx_100yr_discharge\",\n    walkers_output=\"rx_100yr_walkers\",\n    rain=\"rainfall_excess\",  # Infiltration / Veg Intercept\n    man=\"mannings_n\",  # Mixed forest Kalyanapu et al. (2009)\n    nwalkers=1000000,\n    # infil=\"ksat_r_sda\", # Infiltration of flowing water\n    # niterations=1440 / 2,\n    duration=duration_min, # Duration of the simulated water flow [minutes]\n    output_step=2, # Time interval for creating output maps [minutes]\n    nprocs=30,\n    flags=\"t\",\n)\n\n# Register the output maps into a space time dataset\ngs.run_command(\n    \"t.create\",\n    output=\"rx_100yr_depth_sum\",\n    type=\"strds\",\n    temporaltype=\"absolute\",\n    title=\"Runoff Depth\",\n    description=\"Runoff Depth in [m]\",\n    overwrite=True,\n)\n\n# Get the list of depth maps\ndepth_list = gs.read_command(\n    \"g.list\", type=\"raster\", pattern=\"rx_100yr_depth.*\", separator=\"comma\"\n).strip()\n\n# Register the maps\ngs.run_command(\n    \"t.register\",\n    input=\"rx_100yr_depth_sum\",\n    type=\"raster\",\n    start=\"2024-01-01\",\n    increment=\"2 minutes\",\n    maps=depth_list,\n    flags=\"i\",\n    overwrite=True,\n)\n```\n:::\n\n\n::: {#rx_100yr_depth_map .cell execution_count=31}\n``` {.python .cell-code}\ndepth_list = gs.read_command(\n    \"g.list\", type=\"raster\", pattern=\"rx_100yr_depth.*\", separator=\"comma\"\n).strip()\n\nmax_depth = depth_list.split(\",\")[-1]\nstats = tools.r_info(map=max_depth, format=\"json\").json\n\ndef parse_simwe_comments(comments: str) -> pd.DataFrame:\n    params = {}\n    for line in comments.strip().splitlines():\n        for part in line.split(\",\"):\n            part = part.strip()\n            if \"=\" in part:\n                k, v = part.split(\"=\", 1)\n                k = k.strip()\n                v = v.strip().strip('\"')\n                try:\n                    v = float(v) if \".\" in v or \"e\" in v.lower() else int(v)\n                except ValueError:\n                    pass\n                params[k] = v\n    return (\n        pd.DataFrame(list(params.items()), columns=[\"Parameter\", \"Value\"])\n    )\n\ndisplay(\n    parse_simwe_comments(stats[\"comments\"])\n    .style.hide(axis=\"index\")\n    .set_caption(f\"r.sim.water run summary — {max_depth}\")\n)\n\nwith gs.RegionManager(raster=\"accumulation\", s=\"s-300\", flags=\"a\"):\n    m = gj.Map(use_region=True, width=600)\n    m.d_shade(shade=\"relief\", color=\"naip_2021_rgb@naip\")\n    m.d_rast(map=max_depth, values=f\"0.025-{stats['max']}\")\n    m.d_legend(\n        raster=max_depth,\n        at=\"8, 12, 20, 80\",\n        title=\"Depth [m]\",\n        font=\"Fira Sans Condensed Light\",\n        range=[0.025, stats[\"max\"]],\n        fontsize=16,\n        flags=\"s\",\n    )\n    m.d_barscale(\n        at=(67, 19),\n        font=\"Fira Sans Condensed Light\",\n        fontsize=12,\n        length=250,\n        unit=\"meters\",\n        width_scale=1,\n        bgcolor=\"none\",\n        # style=\"both_ticks\",\n        color=\"#4f4e4e\",\n        flags=\"n\",\n    )\n    m.show()\n```\n\n::: {#rx_100yr_depth_map-1 .cell-output .cell-output-display}\n```{=html}\n<style type=\"text/css\">\n</style>\n<table id=\"T_36c5f\">\n  <caption>r.sim.water run summary — rx_100yr_depth.53</caption>\n  <thead>\n    <tr>\n      <th id=\"T_36c5f_level0_col0\" class=\"col_heading level0 col0\" >Parameter</th>\n      <th id=\"T_36c5f_level0_col1\" class=\"col_heading level0 col1\" >Value</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td id=\"T_36c5f_row0_col0\" class=\"data row0 col0\" >init.walk</td>\n      <td id=\"T_36c5f_row0_col1\" class=\"data row0 col1\" >1152606</td>\n    </tr>\n    <tr>\n      <td id=\"T_36c5f_row1_col0\" class=\"data row1 col0\" >maxwalk</td>\n      <td id=\"T_36c5f_row1_col1\" class=\"data row1 col1\" >1000000</td>\n    </tr>\n    <tr>\n      <td id=\"T_36c5f_row2_col0\" class=\"data row2 col0\" >remaining walkers</td>\n      <td id=\"T_36c5f_row2_col1\" class=\"data row2 col1\" >933052</td>\n    </tr>\n    <tr>\n      <td id=\"T_36c5f_row3_col0\" class=\"data row3 col0\" >duration (sec.)</td>\n      <td id=\"T_36c5f_row3_col1\" class=\"data row3 col1\" >3240</td>\n    </tr>\n    <tr>\n      <td id=\"T_36c5f_row4_col0\" class=\"data row4 col0\" >time-series iteration</td>\n      <td id=\"T_36c5f_row4_col1\" class=\"data row4 col1\" >3180</td>\n    </tr>\n    <tr>\n      <td id=\"T_36c5f_row5_col0\" class=\"data row5 col0\" >written deltap</td>\n      <td id=\"T_36c5f_row5_col1\" class=\"data row5 col1\" >0.684773</td>\n    </tr>\n    <tr>\n      <td id=\"T_36c5f_row6_col0\" class=\"data row6 col0\" >mean vel.</td>\n      <td id=\"T_36c5f_row6_col1\" class=\"data row6 col1\" >1.095253</td>\n    </tr>\n    <tr>\n      <td id=\"T_36c5f_row7_col0\" class=\"data row7 col0\" >mean source (si)</td>\n      <td id=\"T_36c5f_row7_col1\" class=\"data row7 col1\" >0.000011</td>\n    </tr>\n    <tr>\n      <td id=\"T_36c5f_row8_col0\" class=\"data row8 col0\" >mean infil</td>\n      <td id=\"T_36c5f_row8_col1\" class=\"data row8 col1\" >0.000000</td>\n    </tr>\n    <tr>\n      <td id=\"T_36c5f_row9_col0\" class=\"data row9 col0\" >r.sim.water -t elevation</td>\n      <td id=\"T_36c5f_row9_col1\" class=\"data row9 col1\" >elevation\" rain=\"rainfall_excess\" rain_value=50 infil_value=0.0 man=\"mannings_n\" man_value=0.1 depth=\"rx_100yr_depth\" discharge=\"rx_100yr_discharge\" walkers_output=\"rx_100yr_walkers\" nwalkers=1000000 duration=54.05 mintimestep=0.0 output_step=2 diffusion_coeff=0.8 hmax=0.3 halpha=4.0 hbeta=0.5 nprocs=30</td>\n    </tr>\n  </tbody>\n</table>\n```\n\nRunoff depth map derived from the r.sim.water tool for a 100-year storm with soil data, visualized at the last outputed time step.\n:::\n\n::: {.cell-output .cell-output-display}\n![](ssurgo_clay_center_files/figure-html/rx_100yr_depth_map-output-2.png){#rx_100yr_depth_map-2}\n:::\n:::\n\n\nThe animation below shows flow depth evolving over the 54-minute storm. Runoff concentrates in the drainage channels, with depth patterns reflecting the upstream soil and land-cover mosaic encoded in the rainfall-excess raster.\n\n::: {#tc_100_depth_map .cell execution_count=32}\n``` {.python .cell-code}\nmax_depth = depth_list.split(\",\")[-1]\nstats = tools.r_info(map=max_depth, format=\"json\").json\nwith gs.RegionManager(raster=\"accumulation\", s=\"s-300\", flags=\"a\"):\n    m = gj.TimeSeriesMap(use_region=True, width=600)\n    m.d_rast(map=\"naip_2021_rgb@naip\")\n    m.add_raster_series(\"rx_100yr_depth_sum\", values=f\"0.005-{stats['max']}\")\n    m.d_legend(\n        raster=max_depth,\n        title=\"Depth [m]\",\n        flags=\"bt\",\n        border_color=\"none\",\n        range=[0.005, stats[\"max\"]],\n        at=\"8, 12, 20, 80\",\n    )\n    m.d_barscale(\n        at=(67, 19),\n        font=\"Fira Sans Condensed Light\",\n        fontsize=12,\n        length=250,\n        unit=\"meters\",\n        width_scale=1,\n        bgcolor=\"none\",\n        color=\"#4f4e4e\",\n        flags=\"n\",\n    )\n\n    m.save(\"output/clay_center_rx_100yr_simwe_depth_animation.gif\")\n    m.show()\n```\n:::\n\n\n![Overland Flow Simulation with Soil Data](output/clay_center_rx_100yr_simwe_depth_animation.gif)\n\n### Simulation B: Uniform Rainfall (No Soil Correction)\n\nFor comparison, we run the same storm as a uniform rainfall rate applied equally to every cell -- the approach one would take without soil data. Here `rain_value` is set to the full 100-year intensity (approximately 102 mm/hr) with no curve-number reduction. Every cell generates runoff as if its soil were impervious, so we expect uniformly higher flow depths and no spatial differentiation driven by soil properties.\n\n::: {#r_sim_water_no_soil .cell execution_count=33}\n``` {.python .cell-code}\nintensity_mm_hr = 101.937\ntools.r_sim_water(\n    elevation=\"elevation\",\n    depth=\"basic_depth\",\n    discharge=\"basic_disch\",\n    walkers_output=\"basic_particles\",\n    rain_value=intensity_mm_hr,  # Rainfall intensity: 95.584 mm/hr\n    man=\"mannings_n\",  # Mixed forest Kalyanapu et al. (2009)\n    nwalkers=1000000,\n    # infil=\"ksat_r_sda\", # Infiltration of flowing water\n    niterations=duration_min,\n    output_step=2,\n    nprocs=30,\n    flags=\"t\",\n)\n\ngs.run_command(\n    \"t.create\",\n    output=\"basic_depth_sum\",\n    type=\"strds\",\n    temporaltype=\"absolute\",\n    title=\"Runoff Depth\",\n    description=\"Runoff Depth in [m]\",\n    overwrite=True,\n)\n\n# Get the list of depth maps\ndepth_list = gs.read_command(\n    \"g.list\", type=\"raster\", pattern=\"basic_depth.*\", separator=\"comma\"\n).strip()\n\n# Register the maps\ngs.run_command(\n    \"t.register\",\n    input=\"basic_depth_sum\",\n    type=\"raster\",\n    start=\"2024-01-01\",\n    increment=\"2 minutes\",\n    maps=depth_list,\n    flags=\"i\",\n    overwrite=True,\n)\n```\n:::\n\n\n::: {#c463ca93 .cell execution_count=34}\n``` {.python .cell-code}\ndepth_list = gs.read_command(\n    \"g.list\", type=\"raster\", pattern=\"basic_depth.*\", separator=\"comma\"\n).strip()\n\nbasic_max_depth = depth_list.split(\",\")[-1]\nstats = tools.r_info(map=basic_max_depth, format=\"json\").json\nwith gs.RegionManager(raster=\"accumulation\", s=\"s-300\", flags=\"a\"):\n    m = gj.Map(use_region=True, width=600)\n    m.d_shade(shade=\"relief\", color=\"naip_2021_rgb@naip\")\n    m.d_rast(map=basic_max_depth, values=f\"0.025-{stats['max']}\")\n    m.d_legend(\n        raster=basic_max_depth,\n        at=\"8, 12, 20, 80\",\n        title=\"Depth [m]\",\n        font=\"Fira Sans Condensed Light\",\n        range=[0.025, stats[\"max\"]],\n        fontsize=16,\n        flags=\"s\",\n    )\n    m.d_barscale(\n        at=(67, 19),\n        font=\"Fira Sans Condensed Light\",\n        fontsize=12,\n        length=250,\n        unit=\"meters\",\n        width_scale=1,\n        bgcolor=\"none\",\n        # style=\"both_ticks\",\n        color=\"#4f4e4e\",\n        flags=\"n\",\n    )\n    m.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ssurgo_clay_center_files/figure-html/cell-35-output-1.png){}\n:::\n:::\n\n\nThe uniform-rainfall animation shows noticeably deeper flow everywhere compared to the soil-informed run. Without soil-based partitioning, the model treats the entire landscape as equally impervious, overestimating runoff from permeable soils and losing the spatial heterogeneity visible in the soil-informed results.\n\n::: {#basic_depth_map_animation .cell execution_count=35}\n``` {.python .cell-code}\nbasic_max_depth = depth_list.split(\",\")[-1]\nstats = tools.r_info(map=basic_max_depth, format=\"json\").json\nwith gs.RegionManager(raster=\"accumulation\", s=\"s-300\", flags=\"a\"):\n    m = gj.TimeSeriesMap(use_region=True, width=600)\n    m.d_rast(map=\"naip_2021_rgb@naip\")\n    m.add_raster_series(\"basic_depth_sum\", values=f\"0.005-{stats['max']}\")\n    m.d_legend(\n        raster=basic_max_depth,\n        title=\"Depth [m]\",\n        flags=\"bt\",\n        border_color=\"none\",\n        range=[0.005, stats[\"max\"]],\n        at=\"8, 12, 20, 80\",\n    )\n    m.d_barscale(\n        at=(67, 19),\n        font=\"Fira Sans Condensed Light\",\n        fontsize=12,\n        length=250,\n        unit=\"meters\",\n        width_scale=1,\n        bgcolor=\"none\",\n        # style=\"both_ticks\",\n        color=\"#4f4e4e\",\n        flags=\"n\",\n    )\n    m.save(\"output/clay_center_basic_depth_simwe_depth_animation.gif\")\n    m.show()\n```\n:::\n\n\n![Overland Flow Simulation without Soil Data](output/clay_center_basic_depth_simwe_depth_animation.gif)\n\n### Comparing the Two Simulations\n\nTo quantify the effect of soil-informed rainfall excess, we compare the final-timestep depth rasters from both runs. The difference map (uniform minus soil-informed) highlights where and by how much the uniform assumption overestimates water depth.\n\n::: {#cell-comparison_difference_map .cell execution_count=36}\n\n::: {.cell-output .cell-output-display}\n![Difference in simulated flow depth (uniform rainfall minus soil-informed rainfall excess) at the final time step. Positive values (blue) indicate locations where the uniform assumption overestimates depth.](ssurgo_clay_center_files/figure-html/comparison_difference_map-output-1.png){#comparison_difference_map}\n:::\n:::\n\n\nSide-by-side comparison of the final-timestep flow depth for both simulations, displayed on the same color scale for direct visual comparison.\n\n::: {#comparison_side_by_side .cell layout-ncol='2' execution_count=37}\n\n::: {.cell-output .cell-output-display}\n![Soil-Informed Rainfall Excess](ssurgo_clay_center_files/figure-html/comparison_side_by_side-output-1.png){#comparison_side_by_side-1}\n:::\n\n::: {.cell-output .cell-output-display}\n![Uniform Rainfall](ssurgo_clay_center_files/figure-html/comparison_side_by_side-output-2.png){#comparison_side_by_side-2}\n:::\n\nFinal-timestep flow depth comparison using a shared color scale.\n:::\n\n\nSummary statistics for both simulations and the difference raster, showing how uniform rainfall systematically overestimates flow depth.\n\n::: {#cell-comparison_statistics .cell execution_count=38}\n\n::: {#comparison_statistics .cell-output .cell-output-display}\n```{=html}\n<style type=\"text/css\">\n</style>\n<table id=\"T_dc8f3\">\n  <caption>Flow Depth Summary Statistics — Final Time Step</caption>\n  <thead>\n    <tr>\n      <th id=\"T_dc8f3_level0_col0\" class=\"col_heading level0 col0\" >Statistic</th>\n      <th id=\"T_dc8f3_level0_col1\" class=\"col_heading level0 col1\" >Soil-Informed (m)</th>\n      <th id=\"T_dc8f3_level0_col2\" class=\"col_heading level0 col2\" >Uniform Rainfall (m)</th>\n      <th id=\"T_dc8f3_level0_col3\" class=\"col_heading level0 col3\" >Difference (m)</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td id=\"T_dc8f3_row0_col0\" class=\"data row0 col0\" >Mean</td>\n      <td id=\"T_dc8f3_row0_col1\" class=\"data row0 col1\" >0.0289</td>\n      <td id=\"T_dc8f3_row0_col2\" class=\"data row0 col2\" >0.0559</td>\n      <td id=\"T_dc8f3_row0_col3\" class=\"data row0 col3\" >0.0272</td>\n    </tr>\n    <tr>\n      <td id=\"T_dc8f3_row1_col0\" class=\"data row1 col0\" >Std Dev</td>\n      <td id=\"T_dc8f3_row1_col1\" class=\"data row1 col1\" >0.0634</td>\n      <td id=\"T_dc8f3_row1_col2\" class=\"data row1 col2\" >0.1023</td>\n      <td id=\"T_dc8f3_row1_col3\" class=\"data row1 col3\" >0.0507</td>\n    </tr>\n    <tr>\n      <td id=\"T_dc8f3_row2_col0\" class=\"data row2 col0\" >Min</td>\n      <td id=\"T_dc8f3_row2_col1\" class=\"data row2 col1\" >0.0005</td>\n      <td id=\"T_dc8f3_row2_col2\" class=\"data row2 col2\" >0.0010</td>\n      <td id=\"T_dc8f3_row2_col3\" class=\"data row2 col3\" >-0.0013</td>\n    </tr>\n    <tr>\n      <td id=\"T_dc8f3_row3_col0\" class=\"data row3 col0\" >Max</td>\n      <td id=\"T_dc8f3_row3_col1\" class=\"data row3 col1\" >0.9596</td>\n      <td id=\"T_dc8f3_row3_col2\" class=\"data row3 col2\" >1.3422</td>\n      <td id=\"T_dc8f3_row3_col3\" class=\"data row3 col3\" >0.4827</td>\n    </tr>\n    <tr>\n      <td id=\"T_dc8f3_row4_col0\" class=\"data row4 col0\" >Median</td>\n      <td id=\"T_dc8f3_row4_col1\" class=\"data row4 col1\" >0.0097</td>\n      <td id=\"T_dc8f3_row4_col2\" class=\"data row4 col2\" >0.0189</td>\n      <td id=\"T_dc8f3_row4_col3\" class=\"data row4 col3\" >0.0087</td>\n    </tr>\n  </tbody>\n</table>\n```\n:::\n:::\n\n\n::: {#cell-comparison_histogram .cell execution_count=39}\n\n::: {.cell-output .cell-output-display}\n![Distribution of flow depth at the final time step for both simulations. The uniform-rainfall run (orange) is shifted toward higher depths relative to the soil-informed run (blue).](ssurgo_clay_center_files/figure-html/comparison_histogram-output-1.png){#comparison_histogram width=926 height=544}\n:::\n:::\n\n\n## Discussion and Conclusions\n\nThe comparison above quantifies the practical value of soil-informed rainfall excess:\n\n- **Spatial pattern.** The difference map shows that the uniform-rainfall assumption does not simply scale depths up everywhere -- it shifts the spatial distribution of runoff. The soil-informed run produces heterogeneous flow depths that reflect the underlying soil--cover mosaic, with channels draining clay-rich cropland carrying more water than those draining grassland on loamier soils. The uniform run loses this differentiation.\n\n- **Magnitude.** The summary statistics and histogram confirm that uniform rainfall systematically overestimates flow depth. In areas with group-B soils and low curve numbers, the overestimate is largest because those cells absorb a substantial fraction of rainfall that the uniform model ignores entirely.\n\n- **Implications for management.** Accurate runoff prediction matters for conservation planning, infrastructure sizing, and flood-risk assessment. Using freely available SSURGO data to spatially distribute rainfall excess is a low-cost improvement over uniform assumptions, especially in agricultural watersheds where soil variability is high.\n\n### Limitations and Next Steps\n\n- The SCS curve-number method assumes a single antecedent moisture condition (AMC II). Wet or dry antecedent conditions would shift CN values and change runoff depths.\n- Ksat-based continuous infiltration (via the SIMWE `infil` parameter) could complement or replace the event-based CN approach for longer or multi-event simulations.\n- Comparing discharge (not just depth) between the two runs would further quantify the hydrologic impact of soil data on peak flow predictions.\n\n",
        "supporting": [
            "ssurgo_clay_center_files"
        ],
        "filters": [],
        "includes": {
            "include-in-header": [
                "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
            ]
        }
    }
}
