{
    "hash": "61150d5b50214d89f05a991a210dbe36",
    "result": {
        "engine": "jupyter",
        "markdown": "---\njupyter: python3\nauthor: Corey T. White\nimage: output/coweeta_ksat_r_sda.png\nexecute:\n  eval: true\n  freeze: auto\ndate-modified: today\nformat:\n  html:\n    toc: true\n    code-tools: true\n    code-copy: true\n    code-fold: true\n    mermaid:\n      theme: forest\n    lightbox: true\ntitle: Study Area\n---\n\n\n\n# Coweeta, NC -- Soil-Informed Overland Flow Simulation\n\nThe Coweeta Hydrologic Laboratory sits in the southern Blue Ridge Mountains of western North Carolina, where steep slopes, dense mixed-hardwood canopy, and deep well-drained loams route most rainfall through subsurface pathways long before it reaches a channel. That makes Coweeta a demanding test for overland-flow models: soil and cover heterogeneity fundamentally reshape where runoff forms and how fast it travels. Typical shallow-water runs apply a single uniform rainfall rate to every cell, but real rainfall excess -- the fraction of precipitation that actually runs off -- varies pixel by pixel. This notebook imports USDA SSURGO soil data, derives a spatially varying rainfall-excess surface via SCS curve-number analysis, and feeds it into the SIMWE particle-based shallow-water model. We then compare the soil-informed simulation against a naive one that ignores soil variability, and animate the walker cloud colored by flow speed.\n\nThe workflow below (@fig_ssurgo_flowchart) traces data from SSURGO and NLCD inputs through curve number, time of concentration, and Manning's $n$ to SIMWE's depth, discharge, and walker outputs.\n\n```{mermaid}\n%% label: fig_ssurgo_flowchart\n%% echo: false\n%% eval: true\n%% fig-cap: \"(Draft) Flowchart of SSURGO SIMWE workflows\"\nflowchart TD\n    A[r.in.ssurgo] --> B(\"Soils map vector\")\n    A[r.in.ssurgo] --> HG(\"Hydrologic group map\")\n    A[r.in.ssurgo] --> KSAT(\"Ksat maps rasters\")\n    A[r.in.ssurgo] --> E(\"MUKEY map raster\")\n    B --> F(\"Soil attributes in vector attribute table\")\n    G[r.curvenumber] --> H(\"Curve number map\")\n    HG --> G\n    LC(NLCD land cover map) --> G\n    ELEV[Elevation raster] --> W[r.watershed]\n    W --> I(\"Flow direction\")\n    W --> J(\"Streams\")\n    W --> K(\"Basins\")\n    TC[r.timeofconcentration] --> TCR(\"Time of concentration\")\n    ELEV --> TC\n    I --> TC\n    J --> TC\n    H --> R[r.runoff]\n    I --> R\n    TCR --> R\n    R --> RD(\"Runoff depth\")\n    R --> RV(\"Runoff volume\")\n    R --> TP(\"Time to peak\")\n    R --> PD(\"Peak discharge raster\")\n    R --> URD(\"Upstream runoff depth\")\n    R --> URV(\"Upstream runoff volume\")\n    R --> UA(\"Upstream area\")\n    LC --> MC[\"r.manning\"]\n    MC --> MN(\"Manning's n map\")\n    ELEV --> RSA[\"r.slope.aspect\"]\n    RSA --> DX(\"dx\")\n    RSA --> DY(\"dy\")\n    ELEV --> SIMWE[\"r.sim.water\"]\n    DX --> SIMWE\n    DY --> SIMWE\n    MN --> SIMWE\n    HG --> SIMWE\n    KSAT --> SIMWE\n    SIMWE --> DEPTH(\"Water depth raster\")\n    SIMWE --> DISCHARGE(\"Discharge raster\")\n```\n\n## Objectives\n\n1. Import SSURGO soil properties (hydrologic groups, saturated hydraulic conductivity, MUKEYs) from either a local gSSURGO archive or the USDA Soil Data Access service.\n2. Derive a curve-number surface by combining hydrologic soil groups with NLCD 2024 land cover.\n3. Design a 100-year storm whose duration matches the watershed's time of concentration, ensuring peak-runoff conditions.\n4. Convert SCS curve-number runoff depths into a spatially varying rainfall-excess rate (mm/hr) suitable for SIMWE.\n5. Compute Manning's $n$ from NLCD to parameterize surface roughness for the shallow-water solver.\n6. Run SIMWE with and without soil-informed rainfall excess, then visualize the walker cloud colored by flow speed ($v = q/h$) from the model's own depth and discharge outputs.\n\n\n\n\nCoweeta Hydrologic Laboratory (35.0667 N, 83.4333 W) is a long-term USDA Forest Service research site near Otto, NC, with ~2700 ft (~820 m) of relief across forested headwater catchments. Hydrologic soil groups here are dominated by **B** (moderate infiltration) with pockets of **C** and **D** on thinner ridge soils, in contrast to the B/C/D cropland mosaic at the Clay Center site. Work happens inside a GRASS mapset called `ssurgo_demo` in a project aligned to the site's 3 m elevation raster.\n\n\n\n\n---\n\n## Import SSURGO Data\n\n`r.in.ssurgo` can pull soil survey data in two modes: from a local **gSSURGO** state archive, or on-demand from the **Soil Data Access** (SDA) web service, which avoids the multi-GB download at the cost of network latency. Both modes produce the same outputs -- a soil-polygon vector plus categorical rasters for hydrologic group (HSG) and MUKEY, and low/representative/high saturated hydraulic conductivity ($K_{sat}$) rasters -- which downstream tools use as inputs to curve-number and infiltration models.\n\nSource for the `r.in.ssurgo` addon lives in `tools/r.soildb/r.in.ssurgo` in this repository; install it via `g.extension` pointing at that path (or from the GRASS Addons repository once it's merged).\n\n\n\n### Computational Region\n\nWe align the computational region to the 3 m elevation raster so every derived layer -- soil rasters, curve number, Manning's $n$, SIMWE outputs -- shares the same grid. A companion shaded-relief raster provides the cartographic backdrop for every map that follows.\n\n::: {#set_region .cell execution_count=4}\n``` {.python .cell-code}\nregion_text = tools.g_region(raster=\"elevation\", flags=\"p\").text\nprint(region_text)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nprojection: 1 (UTM)\nzone:       17\ndatum:      nad83\nellipsoid:  grs80\nnorth:      3884960\nsouth:      3876990\nwest:       272970\neast:       280150\nnsres:      10\newres:      10\nrows:       797\ncols:       718\ncells:      572246\n```\n:::\n:::\n\n\n::: {#create_relief .cell execution_count=5}\n``` {.python .cell-code}\ntools.r_relief(input=\"elevation\", output=\"relief\")\n```\n:::\n\n\n### Loading the soil data\n\nThe local tab below imports from a downloaded gSSURGO North Carolina archive; the SDA tab queries the web service directly (no prior download). The horizon window (`hzdept_r=0`, `hzdepb_r=100` cm) and master designation filter (`desgnmaster=\"A\"`) select the top 100 cm of A-horizon material, since rainfall-excess generation on forested slopes is dominated by near-surface soil properties. Outputs are suffixed `_sda` when imported via SDA so both versions can coexist.\n\n\n## SDA Import\n\n::: {#import_ssurgo_sda .cell execution_count=6}\n``` {.python .cell-code}\ntools.r_in_ssurgo(\n    soils=\"soil_areas_sda\",\n    hydgrp=\"hydgrp_sda\",\n    ksat_l=\"ksat_l_sda\",\n    ksat_r=\"ksat_r_sda\",\n    ksat_h=\"ksat_h_sda\",\n    mukey=\"mukey_sda\",\n    hzdept_r=0,\n    hzdepb_r=100,\n    desgnmaster=\"A\",\n    nprocs=30\n)\n```\n:::\n\n\n## Visualize Imported Data\n\nBefore feeding the soil surfaces into hydrologic models, it's worth confirming the imports look right. The soil polygons (`soil_areas_sda`) carry the full SSURGO attribute table -- MUKEY, component percentages, hydrologic group, texture, and permeability by horizon -- while the companion rasters are pre-rendered MUKEY, HSG, and three $K_{sat}$ percentiles (low / representative / high) for fast map algebra.\n\n### MUKEY Map\n\nMUKEY (map-unit key) is the atomic identifier that ties every raster cell back to a row in the SSURGO attribute database. Distinct MUKEY patches mark where component-level differences -- texture, depth, drainage class, percent rock -- vary even when the aggregated hydrologic group stays the same.\n\n::: {#cell-mukey .cell execution_count=7}\n\n::: {.cell-output .cell-output-display}\n![MUKEY patches at Coweeta with soil polygon boundaries overlaid. The mosaic reflects distinct component assemblages even where the aggregated hydrologic group is the same.](ssurgo_files/figure-html/mukey-output-1.png){#mukey}\n:::\n:::\n\n\n### Ksat Maps\n\nSSURGO reports saturated hydraulic conductivity as a low / representative / high percentile triplet that captures within-map-unit variability. Importing all three ($K_{sat,l}$, $K_{sat,r}$, $K_{sat,h}$) lets downstream infiltration models run at the representative value and be stress-tested against the bracketing bounds.\n\n::: {#ksat .cell layout-ncol='3' execution_count=8}\n\n::: {.cell-output .cell-output-display}\n![Low](ssurgo_files/figure-html/ksat-output-1.png){#ksat-1}\n:::\n\n::: {.cell-output .cell-output-display}\n![Representative](ssurgo_files/figure-html/ksat-output-2.png){#ksat-2}\n:::\n\n::: {.cell-output .cell-output-display}\n![High](ssurgo_files/figure-html/ksat-output-3.png){#ksat-3}\n:::\n\nSSURGO saturated hydraulic conductivity at Coweeta, shown for the low, representative, and high estimates within each map unit. The same absolute color ramp (browns = low $K_{sat}$, blues = high) is applied to all three panels so they are directly comparable -- the high-estimate panel is visibly more permeable because it uses the upper-bound $K_{sat}$ within each component.\n:::\n\n\n### Hydrologic Group\n\nHydrologic soil groups (HSG) are a four-class condensation of SSURGO's detailed soil properties into categories **A** (high infiltration, sand/gravel) through **D** (low infiltration, clay/shallow bedrock), with **A/D** marking soils whose behavior depends on drainage. HSG is the direct input to the SCS curve-number lookup table, so any coarseness in this raster propagates into every subsequent runoff calculation.\n\n::: {#cell-hydrologic_group_map .cell layout-ncol='1' execution_count=9}\n\n::: {.cell-output .cell-output-display}\n![Hydrologic soil groups at Coweeta. Group B dominates the ridgeline forest with pockets of C on thinner soils; no group A (high infiltration) appears in this catchment.](ssurgo_files/figure-html/hydrologic_group_map-output-1.png){#hydrologic_group_map}\n:::\n:::\n\n\n## Calculate Curve Number\n\nThe SCS curve number (CN) is an empirical index, from 0 to 100, that captures how much of a given rainfall depth becomes runoff. High CNs mean runoff-prone surfaces (impervious, bare, hydrologic group D); low CNs mean infiltration-dominant surfaces (forested, group A). CN is computed from an HSG × land cover lookup table, so it's the natural bridge between SSURGO's soil classes and NLCD's cover classes.\n\nInstall `r.curvenumber` from the GRASS Addons repository:\n\n```python\n# | label: install_curvenumber_text\n# | eval: false\ntools.g_extension(\n    extension=\"r.curvenumber\",\n)\n```\n\n\n\n### Land Cover\n\nCN requires a land cover raster alongside the HSG raster. We use NLCD 2024, the most recent national land cover product, imported as a cloud-optimized GeoTIFF so the `r.import` call only reads the pixels that fall inside the current computational region.\n\n::: {#import_landcover .cell execution_count=11}\n``` {.python .cell-code}\ntools.r_import(\n    output=\"nlcd_2024\",\n    input=\"<path_to_nlcd_cog>\",\n    extent=\"region\",\n    resolution=\"region\",\n)\n```\n:::\n\n\nThe imported raster carries numeric class codes (21, 41, 42…) but no human-readable labels -- the legend would render as a column of bare numbers. Since `nlcd_2024` lives in PERMANENT and `r.category` only writes to the current mapset, we copy it into `ssurgo_demo` first, then attach the standard NLCD 2024 class names inline.\n\n::: {#cell-landcover_map .cell layout-ncol='1' execution_count=12}\n\n::: {.cell-output .cell-output-display}\n![NLCD 2024 land cover at Coweeta. The canopy is dominated by deciduous and mixed forest with narrow ribbons of developed, open space along valley floors -- a land-cover distribution that pushes most cells toward low curve-number (infiltration-friendly) values in the next step.](ssurgo_files/figure-html/landcover_map-output-1.png){#landcover_map}\n:::\n:::\n\n\n### Deriving the CN raster\n\nWith HSG and NLCD in hand, [`r.curvenumber`](https://grass.osgeo.org/grass-devel/manuals/addons/r.curvenumber.html) applies the standard SCS lookup. `landcover_source=\"nlcd\"` tells the tool to use the NLCD-specific class-to-CN table (rather than the default NCDS or custom tables), which matters because class codes differ across land-cover datasets.\n\n::: {#curvenumber_calc .cell execution_count=13}\n``` {.python .cell-code}\ntools.r_curvenumber(\n    landcover=\"nlcd_2024\",\n    soil=\"hydgrp_sda\",\n    landcover_source=\"nlcd\",\n    output=\"curvenumber\",\n)\n```\n:::\n\n\n::: {#cell-curvenumber_map .cell layout-ncol='1' execution_count=14}\n\n::: {.cell-output .cell-output-display}\n![Curve number at Coweeta derived from NLCD 2024 and hydrologic soil group. Values span 32 (forested soils, heavy infiltration) to 89 (developed patches on group-C soils).](ssurgo_files/figure-html/curvenumber_map-output-1.png){#curvenumber_map}\n:::\n:::\n\n\n## Runoff and Time of Concentration\n\nA CN raster alone doesn't yet tell us how much runoff a particular storm produces -- we also need a design storm depth (how much rain fell) and the watershed's time of concentration $T_c$ (how long the longest flow path takes to drain). Pairing $T_c$ with an IDF curve identifies the storm duration that generates the peak runoff response, which is the storm we want to simulate with SIMWE.\n\n### Extension installs\n\n`r.timeofconcentration`, `r.stream.distance`, and `r.noaa.atlas14` are needed for this section and are pulled from a local checkout of the grass-addons fork.\n\n\n\n\n\n### Design storm from NOAA Atlas 14\n\nNOAA Atlas 14 provides point-based precipitation frequency estimates indexed by return period (1, 2, 5, ... 1000 yr) and duration (5 min to 60 day). A `mode=\"point\"` query at the Coweeta Experimental Station coordinates fetches the local IDF table without triggering the multi-GB regional grid download that `mode=\"grid\"` would.\n\n::: {#noaa_atlas14 .cell execution_count=17}\n``` {.python .cell-code}\noutjson = tools.r_noaa_atlas14(\n    mode=\"point\",\n    statistic=\"intensity\",\n    vector_output=\"noaa_atlas14_station\",\n    coordinates=[-83.4333, 35.0667],\n    unit=\"metric\",\n    series=\"pds\",\n    bound=\"expected\",\n    resample=\"bilinear\",\n).json\n```\n:::\n\n\n### Watershed analysis\n\n`r.runoff` and `r.timeofconcentration` both need a flow-direction raster, a stream network, and (optionally) basin boundaries. `r.watershed` derives all three from the DEM in a single call.\n\n::: {#watershed .cell execution_count=18}\n``` {.python .cell-code}\ntools.r_watershed(\n    elevation=\"elevation\",\n    drainage=\"flow_direction\",\n    accumulation=\"accumulation\",\n    stream=\"stream\",\n    basin=\"basins\",\n    threshold=1000,\n)\n```\n:::\n\n\n::: {#watershed_map .cell layout-ncol='2' execution_count=19}\n\n::: {.cell-output .cell-output-display}\n![Flow accumulation](ssurgo_files/figure-html/watershed_map-output-1.png){#watershed_map-1}\n:::\n\n::: {.cell-output .cell-output-display}\n![Sub-basins](ssurgo_files/figure-html/watershed_map-output-2.png){#watershed_map-2}\n:::\n\nWatershed products derived from the DEM by `r.watershed`. The NOAA Atlas 14 station coordinate is marked on the flow-accumulation panel.\n:::\n\n\n### Time of concentration\n\n`r.timeofconcentration` traces every cell's flow path downstream using the `flow_direction` and `stream` rasters, accumulating travel time to produce a per-cell $T_c$ estimate. `length_min=100` discards flow paths shorter than 100 m as numerical noise. The maximum of this raster is the watershed-scale $T_c$ that drives the design-storm duration below.\n\n::: {#time_of_concentration .cell execution_count=20}\n``` {.python .cell-code}\ntools.r_timeofconcentration(\n    elevation=\"elevation\",\n    direction=\"flow_direction\",\n    stream=\"stream\",\n    length_min=100,  # minimum length of flow path\n    tc=\"time_concentration\",\n)\n```\n:::\n\n\n::: {#cell-time_of_concentration_map .cell layout-ncol='1' execution_count=21}\n\n::: {.cell-output .cell-output-display}\n![Per-cell time of concentration at Coweeta. Values accumulate downstream along flow paths; the maximum sets the storm duration used to size rainfall intensity.](ssurgo_files/figure-html/time_of_concentration_map-output-1.png){#time_of_concentration_map}\n:::\n:::\n\n\nA quick univariate summary confirms the range of $T_c$ values -- the maximum drives the storm duration used to size rainfall intensity in the next step.\n\n::: {#cell-time_of_concentration_stats .cell execution_count=22}\n\n::: {#time_of_concentration_stats .cell-output .cell-output-display}\n```{=html}\n<style type=\"text/css\">\n</style>\n<table id=\"T_f40c0\">\n  <caption>Time of Concentration — Summary Statistics</caption>\n  <thead>\n    <tr>\n      <th id=\"T_f40c0_level0_col0\" class=\"col_heading level0 col0\" >Statistic</th>\n      <th id=\"T_f40c0_level0_col1\" class=\"col_heading level0 col1\" >Value</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td id=\"T_f40c0_row0_col0\" class=\"data row0 col0\" >n</td>\n      <td id=\"T_f40c0_row0_col1\" class=\"data row0 col1\" >55,231.000</td>\n    </tr>\n    <tr>\n      <td id=\"T_f40c0_row1_col0\" class=\"data row1 col0\" >null_cells</td>\n      <td id=\"T_f40c0_row1_col1\" class=\"data row1 col1\" >517,015.000</td>\n    </tr>\n    <tr>\n      <td id=\"T_f40c0_row2_col0\" class=\"data row2 col0\" >cells</td>\n      <td id=\"T_f40c0_row2_col1\" class=\"data row2 col1\" >572,246.000</td>\n    </tr>\n    <tr>\n      <td id=\"T_f40c0_row3_col0\" class=\"data row3 col0\" >min</td>\n      <td id=\"T_f40c0_row3_col1\" class=\"data row3 col1\" >0.011</td>\n    </tr>\n    <tr>\n      <td id=\"T_f40c0_row4_col0\" class=\"data row4 col0\" >max</td>\n      <td id=\"T_f40c0_row4_col1\" class=\"data row4 col1\" >0.783</td>\n    </tr>\n    <tr>\n      <td id=\"T_f40c0_row5_col0\" class=\"data row5 col0\" >range</td>\n      <td id=\"T_f40c0_row5_col1\" class=\"data row5 col1\" >0.772</td>\n    </tr>\n    <tr>\n      <td id=\"T_f40c0_row6_col0\" class=\"data row6 col0\" >mean</td>\n      <td id=\"T_f40c0_row6_col1\" class=\"data row6 col1\" >0.056</td>\n    </tr>\n    <tr>\n      <td id=\"T_f40c0_row7_col0\" class=\"data row7 col0\" >mean_of_abs</td>\n      <td id=\"T_f40c0_row7_col1\" class=\"data row7 col1\" >0.056</td>\n    </tr>\n    <tr>\n      <td id=\"T_f40c0_row8_col0\" class=\"data row8 col0\" >stddev</td>\n      <td id=\"T_f40c0_row8_col1\" class=\"data row8 col1\" >0.079</td>\n    </tr>\n    <tr>\n      <td id=\"T_f40c0_row9_col0\" class=\"data row9 col0\" >variance</td>\n      <td id=\"T_f40c0_row9_col1\" class=\"data row9 col1\" >0.006</td>\n    </tr>\n    <tr>\n      <td id=\"T_f40c0_row10_col0\" class=\"data row10 col0\" >coeff_var</td>\n      <td id=\"T_f40c0_row10_col1\" class=\"data row10 col1\" >141.229</td>\n    </tr>\n    <tr>\n      <td id=\"T_f40c0_row11_col0\" class=\"data row11 col0\" >sum</td>\n      <td id=\"T_f40c0_row11_col1\" class=\"data row11 col1\" >3,077.783</td>\n    </tr>\n    <tr>\n      <td id=\"T_f40c0_row12_col0\" class=\"data row12 col0\" >first_quartile</td>\n      <td id=\"T_f40c0_row12_col1\" class=\"data row12 col1\" >0.022</td>\n    </tr>\n    <tr>\n      <td id=\"T_f40c0_row13_col0\" class=\"data row13 col0\" >median</td>\n      <td id=\"T_f40c0_row13_col1\" class=\"data row13 col1\" >0.032</td>\n    </tr>\n    <tr>\n      <td id=\"T_f40c0_row14_col0\" class=\"data row14 col0\" >third_quartile</td>\n      <td id=\"T_f40c0_row14_col1\" class=\"data row14 col1\" >0.054</td>\n    </tr>\n    <tr>\n      <td id=\"T_f40c0_row15_col0\" class=\"data row15 col0\" >percentile_percentile</td>\n      <td id=\"T_f40c0_row15_col1\" class=\"data row15 col1\" >90.000</td>\n    </tr>\n    <tr>\n      <td id=\"T_f40c0_row16_col0\" class=\"data row16 col0\" >percentile_value</td>\n      <td id=\"T_f40c0_row16_col1\" class=\"data row16 col1\" >0.102</td>\n    </tr>\n  </tbody>\n</table>\n```\n:::\n:::\n\n\n### Matching storm duration to Tc\n\nThe storm that produces the peak runoff response at a given return period has a duration equal to $T_c$. We convert the watershed's $T_c$ from hours to minutes, look up the NOAA Atlas 14 intensity-duration-frequency (IDF) table, and interpolate the 100-year intensity at that duration.\n\n::: {#cell-tc_and_rfi .cell execution_count=23}\n``` {.python .cell-code}\ndf_tc_min = df_tc[[\"min\", \"mean\", \"max\"]].apply(\n    lambda x: round(x * 60, 2)\n)  # convert to minutes\nmax_tc = df_tc_min[\"max\"].max()\nprint(max_tc)\n\n_rf_table = outjson[\"table\"]\n_rf_rps = [str(rp) for rp in _rf_table[\"return_periods_years\"]]\ndf_rf_intensity = pd.DataFrame(\n    [\n        {\"duration\": row[\"duration\"], **{rp: row[\"values\"].get(rp) for rp in _rf_rps}}\n        for row in _rf_table[\"rows\"]\n    ],\n    columns=[\"duration\"] + _rf_rps,\n)\ndisplay(\n    df_rf_intensity.style.hide(axis=\"index\")\n    .set_caption(\"Rainfall Intensity — NOAA Atlas 14, Coweeta, NC\")\n    .format(\n        {\n            \"Value\": lambda v: f\"{v:,.3f}\"\n            if isinstance(v, (int, float, np.number))\n            else v\n        }\n    )\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n46.97\n```\n:::\n\n::: {#tc_and_rfi .cell-output .cell-output-display}\n```{=html}\n<style type=\"text/css\">\n</style>\n<table id=\"T_30452\">\n  <caption>Rainfall Intensity — NOAA Atlas 14, Coweeta, NC</caption>\n  <thead>\n    <tr>\n      <th id=\"T_30452_level0_col0\" class=\"col_heading level0 col0\" >duration</th>\n      <th id=\"T_30452_level0_col1\" class=\"col_heading level0 col1\" >1</th>\n      <th id=\"T_30452_level0_col2\" class=\"col_heading level0 col2\" >2</th>\n      <th id=\"T_30452_level0_col3\" class=\"col_heading level0 col3\" >5</th>\n      <th id=\"T_30452_level0_col4\" class=\"col_heading level0 col4\" >10</th>\n      <th id=\"T_30452_level0_col5\" class=\"col_heading level0 col5\" >25</th>\n      <th id=\"T_30452_level0_col6\" class=\"col_heading level0 col6\" >50</th>\n      <th id=\"T_30452_level0_col7\" class=\"col_heading level0 col7\" >100</th>\n      <th id=\"T_30452_level0_col8\" class=\"col_heading level0 col8\" >200</th>\n      <th id=\"T_30452_level0_col9\" class=\"col_heading level0 col9\" >500</th>\n      <th id=\"T_30452_level0_col10\" class=\"col_heading level0 col10\" >1000</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td id=\"T_30452_row0_col0\" class=\"data row0 col0\" >5-min</td>\n      <td id=\"T_30452_row0_col1\" class=\"data row0 col1\" >123.000000</td>\n      <td id=\"T_30452_row0_col2\" class=\"data row0 col2\" >144.000000</td>\n      <td id=\"T_30452_row0_col3\" class=\"data row0 col3\" >166.000000</td>\n      <td id=\"T_30452_row0_col4\" class=\"data row0 col4\" >192.000000</td>\n      <td id=\"T_30452_row0_col5\" class=\"data row0 col5\" >220.000000</td>\n      <td id=\"T_30452_row0_col6\" class=\"data row0 col6\" >246.000000</td>\n      <td id=\"T_30452_row0_col7\" class=\"data row0 col7\" >269.000000</td>\n      <td id=\"T_30452_row0_col8\" class=\"data row0 col8\" >293.000000</td>\n      <td id=\"T_30452_row0_col9\" class=\"data row0 col9\" >323.000000</td>\n      <td id=\"T_30452_row0_col10\" class=\"data row0 col10\" >353.000000</td>\n    </tr>\n    <tr>\n      <td id=\"T_30452_row1_col0\" class=\"data row1 col0\" >10-min</td>\n      <td id=\"T_30452_row1_col1\" class=\"data row1 col1\" >98.000000</td>\n      <td id=\"T_30452_row1_col2\" class=\"data row1 col2\" >115.000000</td>\n      <td id=\"T_30452_row1_col3\" class=\"data row1 col3\" >133.000000</td>\n      <td id=\"T_30452_row1_col4\" class=\"data row1 col4\" >154.000000</td>\n      <td id=\"T_30452_row1_col5\" class=\"data row1 col5\" >175.000000</td>\n      <td id=\"T_30452_row1_col6\" class=\"data row1 col6\" >196.000000</td>\n      <td id=\"T_30452_row1_col7\" class=\"data row1 col7\" >214.000000</td>\n      <td id=\"T_30452_row1_col8\" class=\"data row1 col8\" >232.000000</td>\n      <td id=\"T_30452_row1_col9\" class=\"data row1 col9\" >256.000000</td>\n      <td id=\"T_30452_row1_col10\" class=\"data row1 col10\" >278.000000</td>\n    </tr>\n    <tr>\n      <td id=\"T_30452_row2_col0\" class=\"data row2 col0\" >15-min</td>\n      <td id=\"T_30452_row2_col1\" class=\"data row2 col1\" >82.000000</td>\n      <td id=\"T_30452_row2_col2\" class=\"data row2 col2\" >96.000000</td>\n      <td id=\"T_30452_row2_col3\" class=\"data row2 col3\" >112.000000</td>\n      <td id=\"T_30452_row2_col4\" class=\"data row2 col4\" >130.000000</td>\n      <td id=\"T_30452_row2_col5\" class=\"data row2 col5\" >148.000000</td>\n      <td id=\"T_30452_row2_col6\" class=\"data row2 col6\" >165.000000</td>\n      <td id=\"T_30452_row2_col7\" class=\"data row2 col7\" >180.000000</td>\n      <td id=\"T_30452_row2_col8\" class=\"data row2 col8\" >195.000000</td>\n      <td id=\"T_30452_row2_col9\" class=\"data row2 col9\" >214.000000</td>\n      <td id=\"T_30452_row2_col10\" class=\"data row2 col10\" >232.000000</td>\n    </tr>\n    <tr>\n      <td id=\"T_30452_row3_col0\" class=\"data row3 col0\" >30-min</td>\n      <td id=\"T_30452_row3_col1\" class=\"data row3 col1\" >56.000000</td>\n      <td id=\"T_30452_row3_col2\" class=\"data row3 col2\" >66.000000</td>\n      <td id=\"T_30452_row3_col3\" class=\"data row3 col3\" >80.000000</td>\n      <td id=\"T_30452_row3_col4\" class=\"data row3 col4\" >94.000000</td>\n      <td id=\"T_30452_row3_col5\" class=\"data row3 col5\" >110.000000</td>\n      <td id=\"T_30452_row3_col6\" class=\"data row3 col6\" >124.000000</td>\n      <td id=\"T_30452_row3_col7\" class=\"data row3 col7\" >138.000000</td>\n      <td id=\"T_30452_row3_col8\" class=\"data row3 col8\" >152.000000</td>\n      <td id=\"T_30452_row3_col9\" class=\"data row3 col9\" >171.000000</td>\n      <td id=\"T_30452_row3_col10\" class=\"data row3 col10\" >188.000000</td>\n    </tr>\n    <tr>\n      <td id=\"T_30452_row4_col0\" class=\"data row4 col0\" >60-min</td>\n      <td id=\"T_30452_row4_col1\" class=\"data row4 col1\" >35.000000</td>\n      <td id=\"T_30452_row4_col2\" class=\"data row4 col2\" >42.000000</td>\n      <td id=\"T_30452_row4_col3\" class=\"data row4 col3\" >51.000000</td>\n      <td id=\"T_30452_row4_col4\" class=\"data row4 col4\" >61.000000</td>\n      <td id=\"T_30452_row4_col5\" class=\"data row4 col5\" >73.000000</td>\n      <td id=\"T_30452_row4_col6\" class=\"data row4 col6\" >84.000000</td>\n      <td id=\"T_30452_row4_col7\" class=\"data row4 col7\" >95.000000</td>\n      <td id=\"T_30452_row4_col8\" class=\"data row4 col8\" >107.000000</td>\n      <td id=\"T_30452_row4_col9\" class=\"data row4 col9\" >122.000000</td>\n      <td id=\"T_30452_row4_col10\" class=\"data row4 col10\" >137.000000</td>\n    </tr>\n    <tr>\n      <td id=\"T_30452_row5_col0\" class=\"data row5 col0\" >2-hr</td>\n      <td id=\"T_30452_row5_col1\" class=\"data row5 col1\" >21.000000</td>\n      <td id=\"T_30452_row5_col2\" class=\"data row5 col2\" >25.000000</td>\n      <td id=\"T_30452_row5_col3\" class=\"data row5 col3\" >30.000000</td>\n      <td id=\"T_30452_row5_col4\" class=\"data row5 col4\" >36.000000</td>\n      <td id=\"T_30452_row5_col5\" class=\"data row5 col5\" >43.000000</td>\n      <td id=\"T_30452_row5_col6\" class=\"data row5 col6\" >49.000000</td>\n      <td id=\"T_30452_row5_col7\" class=\"data row5 col7\" >56.000000</td>\n      <td id=\"T_30452_row5_col8\" class=\"data row5 col8\" >63.000000</td>\n      <td id=\"T_30452_row5_col9\" class=\"data row5 col9\" >72.000000</td>\n      <td id=\"T_30452_row5_col10\" class=\"data row5 col10\" >81.000000</td>\n    </tr>\n    <tr>\n      <td id=\"T_30452_row6_col0\" class=\"data row6 col0\" >3-hr</td>\n      <td id=\"T_30452_row6_col1\" class=\"data row6 col1\" >15.000000</td>\n      <td id=\"T_30452_row6_col2\" class=\"data row6 col2\" >18.000000</td>\n      <td id=\"T_30452_row6_col3\" class=\"data row6 col3\" >22.000000</td>\n      <td id=\"T_30452_row6_col4\" class=\"data row6 col4\" >26.000000</td>\n      <td id=\"T_30452_row6_col5\" class=\"data row6 col5\" >31.000000</td>\n      <td id=\"T_30452_row6_col6\" class=\"data row6 col6\" >36.000000</td>\n      <td id=\"T_30452_row6_col7\" class=\"data row6 col7\" >41.000000</td>\n      <td id=\"T_30452_row6_col8\" class=\"data row6 col8\" >46.000000</td>\n      <td id=\"T_30452_row6_col9\" class=\"data row6 col9\" >54.000000</td>\n      <td id=\"T_30452_row6_col10\" class=\"data row6 col10\" >61.000000</td>\n    </tr>\n    <tr>\n      <td id=\"T_30452_row7_col0\" class=\"data row7 col0\" >6-hr</td>\n      <td id=\"T_30452_row7_col1\" class=\"data row7 col1\" >10.000000</td>\n      <td id=\"T_30452_row7_col2\" class=\"data row7 col2\" >12.000000</td>\n      <td id=\"T_30452_row7_col3\" class=\"data row7 col3\" >14.000000</td>\n      <td id=\"T_30452_row7_col4\" class=\"data row7 col4\" >17.000000</td>\n      <td id=\"T_30452_row7_col5\" class=\"data row7 col5\" >20.000000</td>\n      <td id=\"T_30452_row7_col6\" class=\"data row7 col6\" >23.000000</td>\n      <td id=\"T_30452_row7_col7\" class=\"data row7 col7\" >26.000000</td>\n      <td id=\"T_30452_row7_col8\" class=\"data row7 col8\" >30.000000</td>\n      <td id=\"T_30452_row7_col9\" class=\"data row7 col9\" >35.000000</td>\n      <td id=\"T_30452_row7_col10\" class=\"data row7 col10\" >39.000000</td>\n    </tr>\n    <tr>\n      <td id=\"T_30452_row8_col0\" class=\"data row8 col0\" >12-hr</td>\n      <td id=\"T_30452_row8_col1\" class=\"data row8 col1\" >7.000000</td>\n      <td id=\"T_30452_row8_col2\" class=\"data row8 col2\" >8.000000</td>\n      <td id=\"T_30452_row8_col3\" class=\"data row8 col3\" >9.000000</td>\n      <td id=\"T_30452_row8_col4\" class=\"data row8 col4\" >11.000000</td>\n      <td id=\"T_30452_row8_col5\" class=\"data row8 col5\" >13.000000</td>\n      <td id=\"T_30452_row8_col6\" class=\"data row8 col6\" >14.000000</td>\n      <td id=\"T_30452_row8_col7\" class=\"data row8 col7\" >16.000000</td>\n      <td id=\"T_30452_row8_col8\" class=\"data row8 col8\" >18.000000</td>\n      <td id=\"T_30452_row8_col9\" class=\"data row8 col9\" >20.000000</td>\n      <td id=\"T_30452_row8_col10\" class=\"data row8 col10\" >23.000000</td>\n    </tr>\n    <tr>\n      <td id=\"T_30452_row9_col0\" class=\"data row9 col0\" >24-hr</td>\n      <td id=\"T_30452_row9_col1\" class=\"data row9 col1\" >4.000000</td>\n      <td id=\"T_30452_row9_col2\" class=\"data row9 col2\" >5.000000</td>\n      <td id=\"T_30452_row9_col3\" class=\"data row9 col3\" >6.000000</td>\n      <td id=\"T_30452_row9_col4\" class=\"data row9 col4\" >7.000000</td>\n      <td id=\"T_30452_row9_col5\" class=\"data row9 col5\" >8.000000</td>\n      <td id=\"T_30452_row9_col6\" class=\"data row9 col6\" >10.000000</td>\n      <td id=\"T_30452_row9_col7\" class=\"data row9 col7\" >11.000000</td>\n      <td id=\"T_30452_row9_col8\" class=\"data row9 col8\" >12.000000</td>\n      <td id=\"T_30452_row9_col9\" class=\"data row9 col9\" >13.000000</td>\n      <td id=\"T_30452_row9_col10\" class=\"data row9 col10\" >15.000000</td>\n    </tr>\n    <tr>\n      <td id=\"T_30452_row10_col0\" class=\"data row10 col0\" >2-day</td>\n      <td id=\"T_30452_row10_col1\" class=\"data row10 col1\" >3.000000</td>\n      <td id=\"T_30452_row10_col2\" class=\"data row10 col2\" >3.000000</td>\n      <td id=\"T_30452_row10_col3\" class=\"data row10 col3\" >4.000000</td>\n      <td id=\"T_30452_row10_col4\" class=\"data row10 col4\" >4.000000</td>\n      <td id=\"T_30452_row10_col5\" class=\"data row10 col5\" >5.000000</td>\n      <td id=\"T_30452_row10_col6\" class=\"data row10 col6\" >6.000000</td>\n      <td id=\"T_30452_row10_col7\" class=\"data row10 col7\" >6.000000</td>\n      <td id=\"T_30452_row10_col8\" class=\"data row10 col8\" >7.000000</td>\n      <td id=\"T_30452_row10_col9\" class=\"data row10 col9\" >8.000000</td>\n      <td id=\"T_30452_row10_col10\" class=\"data row10 col10\" >8.000000</td>\n    </tr>\n    <tr>\n      <td id=\"T_30452_row11_col0\" class=\"data row11 col0\" >3-day</td>\n      <td id=\"T_30452_row11_col1\" class=\"data row11 col1\" >2.000000</td>\n      <td id=\"T_30452_row11_col2\" class=\"data row11 col2\" >2.000000</td>\n      <td id=\"T_30452_row11_col3\" class=\"data row11 col3\" >3.000000</td>\n      <td id=\"T_30452_row11_col4\" class=\"data row11 col4\" >3.000000</td>\n      <td id=\"T_30452_row11_col5\" class=\"data row11 col5\" >3.000000</td>\n      <td id=\"T_30452_row11_col6\" class=\"data row11 col6\" >4.000000</td>\n      <td id=\"T_30452_row11_col7\" class=\"data row11 col7\" >4.000000</td>\n      <td id=\"T_30452_row11_col8\" class=\"data row11 col8\" >5.000000</td>\n      <td id=\"T_30452_row11_col9\" class=\"data row11 col9\" >5.000000</td>\n      <td id=\"T_30452_row11_col10\" class=\"data row11 col10\" >6.000000</td>\n    </tr>\n    <tr>\n      <td id=\"T_30452_row12_col0\" class=\"data row12 col0\" >4-day</td>\n      <td id=\"T_30452_row12_col1\" class=\"data row12 col1\" >1.000000</td>\n      <td id=\"T_30452_row12_col2\" class=\"data row12 col2\" >2.000000</td>\n      <td id=\"T_30452_row12_col3\" class=\"data row12 col3\" >2.000000</td>\n      <td id=\"T_30452_row12_col4\" class=\"data row12 col4\" >2.000000</td>\n      <td id=\"T_30452_row12_col5\" class=\"data row12 col5\" >3.000000</td>\n      <td id=\"T_30452_row12_col6\" class=\"data row12 col6\" >3.000000</td>\n      <td id=\"T_30452_row12_col7\" class=\"data row12 col7\" >3.000000</td>\n      <td id=\"T_30452_row12_col8\" class=\"data row12 col8\" >4.000000</td>\n      <td id=\"T_30452_row12_col9\" class=\"data row12 col9\" >4.000000</td>\n      <td id=\"T_30452_row12_col10\" class=\"data row12 col10\" >4.000000</td>\n    </tr>\n    <tr>\n      <td id=\"T_30452_row13_col0\" class=\"data row13 col0\" >7-day</td>\n      <td id=\"T_30452_row13_col1\" class=\"data row13 col1\" >1.000000</td>\n      <td id=\"T_30452_row13_col2\" class=\"data row13 col2\" >1.000000</td>\n      <td id=\"T_30452_row13_col3\" class=\"data row13 col3\" >1.000000</td>\n      <td id=\"T_30452_row13_col4\" class=\"data row13 col4\" >2.000000</td>\n      <td id=\"T_30452_row13_col5\" class=\"data row13 col5\" >2.000000</td>\n      <td id=\"T_30452_row13_col6\" class=\"data row13 col6\" >2.000000</td>\n      <td id=\"T_30452_row13_col7\" class=\"data row13 col7\" >2.000000</td>\n      <td id=\"T_30452_row13_col8\" class=\"data row13 col8\" >2.000000</td>\n      <td id=\"T_30452_row13_col9\" class=\"data row13 col9\" >3.000000</td>\n      <td id=\"T_30452_row13_col10\" class=\"data row13 col10\" >3.000000</td>\n    </tr>\n    <tr>\n      <td id=\"T_30452_row14_col0\" class=\"data row14 col0\" >10-day</td>\n      <td id=\"T_30452_row14_col1\" class=\"data row14 col1\" >1.000000</td>\n      <td id=\"T_30452_row14_col2\" class=\"data row14 col2\" >1.000000</td>\n      <td id=\"T_30452_row14_col3\" class=\"data row14 col3\" >1.000000</td>\n      <td id=\"T_30452_row14_col4\" class=\"data row14 col4\" >1.000000</td>\n      <td id=\"T_30452_row14_col5\" class=\"data row14 col5\" >1.000000</td>\n      <td id=\"T_30452_row14_col6\" class=\"data row14 col6\" >2.000000</td>\n      <td id=\"T_30452_row14_col7\" class=\"data row14 col7\" >2.000000</td>\n      <td id=\"T_30452_row14_col8\" class=\"data row14 col8\" >2.000000</td>\n      <td id=\"T_30452_row14_col9\" class=\"data row14 col9\" >2.000000</td>\n      <td id=\"T_30452_row14_col10\" class=\"data row14 col10\" >2.000000</td>\n    </tr>\n    <tr>\n      <td id=\"T_30452_row15_col0\" class=\"data row15 col0\" >20-day</td>\n      <td id=\"T_30452_row15_col1\" class=\"data row15 col1\" >1.000000</td>\n      <td id=\"T_30452_row15_col2\" class=\"data row15 col2\" >1.000000</td>\n      <td id=\"T_30452_row15_col3\" class=\"data row15 col3\" >1.000000</td>\n      <td id=\"T_30452_row15_col4\" class=\"data row15 col4\" >1.000000</td>\n      <td id=\"T_30452_row15_col5\" class=\"data row15 col5\" >1.000000</td>\n      <td id=\"T_30452_row15_col6\" class=\"data row15 col6\" >1.000000</td>\n      <td id=\"T_30452_row15_col7\" class=\"data row15 col7\" >1.000000</td>\n      <td id=\"T_30452_row15_col8\" class=\"data row15 col8\" >1.000000</td>\n      <td id=\"T_30452_row15_col9\" class=\"data row15 col9\" >1.000000</td>\n      <td id=\"T_30452_row15_col10\" class=\"data row15 col10\" >1.000000</td>\n    </tr>\n    <tr>\n      <td id=\"T_30452_row16_col0\" class=\"data row16 col0\" >30-day</td>\n      <td id=\"T_30452_row16_col1\" class=\"data row16 col1\" >0.000000</td>\n      <td id=\"T_30452_row16_col2\" class=\"data row16 col2\" >1.000000</td>\n      <td id=\"T_30452_row16_col3\" class=\"data row16 col3\" >1.000000</td>\n      <td id=\"T_30452_row16_col4\" class=\"data row16 col4\" >1.000000</td>\n      <td id=\"T_30452_row16_col5\" class=\"data row16 col5\" >1.000000</td>\n      <td id=\"T_30452_row16_col6\" class=\"data row16 col6\" >1.000000</td>\n      <td id=\"T_30452_row16_col7\" class=\"data row16 col7\" >1.000000</td>\n      <td id=\"T_30452_row16_col8\" class=\"data row16 col8\" >1.000000</td>\n      <td id=\"T_30452_row16_col9\" class=\"data row16 col9\" >1.000000</td>\n      <td id=\"T_30452_row16_col10\" class=\"data row16 col10\" >1.000000</td>\n    </tr>\n    <tr>\n      <td id=\"T_30452_row17_col0\" class=\"data row17 col0\" >45-day</td>\n      <td id=\"T_30452_row17_col1\" class=\"data row17 col1\" >0.000000</td>\n      <td id=\"T_30452_row17_col2\" class=\"data row17 col2\" >0.000000</td>\n      <td id=\"T_30452_row17_col3\" class=\"data row17 col3\" >0.000000</td>\n      <td id=\"T_30452_row17_col4\" class=\"data row17 col4\" >1.000000</td>\n      <td id=\"T_30452_row17_col5\" class=\"data row17 col5\" >1.000000</td>\n      <td id=\"T_30452_row17_col6\" class=\"data row17 col6\" >1.000000</td>\n      <td id=\"T_30452_row17_col7\" class=\"data row17 col7\" >1.000000</td>\n      <td id=\"T_30452_row17_col8\" class=\"data row17 col8\" >1.000000</td>\n      <td id=\"T_30452_row17_col9\" class=\"data row17 col9\" >1.000000</td>\n      <td id=\"T_30452_row17_col10\" class=\"data row17 col10\" >1.000000</td>\n    </tr>\n    <tr>\n      <td id=\"T_30452_row18_col0\" class=\"data row18 col0\" >60-day</td>\n      <td id=\"T_30452_row18_col1\" class=\"data row18 col1\" >0.000000</td>\n      <td id=\"T_30452_row18_col2\" class=\"data row18 col2\" >0.000000</td>\n      <td id=\"T_30452_row18_col3\" class=\"data row18 col3\" >0.000000</td>\n      <td id=\"T_30452_row18_col4\" class=\"data row18 col4\" >0.000000</td>\n      <td id=\"T_30452_row18_col5\" class=\"data row18 col5\" >1.000000</td>\n      <td id=\"T_30452_row18_col6\" class=\"data row18 col6\" >1.000000</td>\n      <td id=\"T_30452_row18_col7\" class=\"data row18 col7\" >1.000000</td>\n      <td id=\"T_30452_row18_col8\" class=\"data row18 col8\" >1.000000</td>\n      <td id=\"T_30452_row18_col9\" class=\"data row18 col9\" >1.000000</td>\n      <td id=\"T_30452_row18_col10\" class=\"data row18 col10\" >1.000000</td>\n    </tr>\n  </tbody>\n</table>\n```\n:::\n:::\n\n\n::: {#rainfall_intensity_figure .cell execution_count=24}\n\n::: {.cell-output .cell-output-display}\n![NOAA Atlas 14 rainfall intensity by storm duration for Coweeta, NC, with the maximum time of concentration marked.](ssurgo_files/figure-html/rainfall_intensity_figure-output-1.png){#rainfall_intensity_figure-1 width=927 height=539}\n:::\n\n::: {#rainfall_intensity_figure-2 .cell-output .cell-output-display}\n```{=html}\n<style type=\"text/css\">\n</style>\n<table id=\"T_d09ba\">\n  <caption>Interpolated rainfall intensity at maximum time of concentration</caption>\n  <thead>\n    <tr>\n      <th id=\"T_d09ba_level0_col0\" class=\"col_heading level0 col0\" >return_period</th>\n      <th id=\"T_d09ba_level0_col1\" class=\"col_heading level0 col1\" >max_tc_min</th>\n      <th id=\"T_d09ba_level0_col2\" class=\"col_heading level0 col2\" >intensity_mm_hr</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td id=\"T_d09ba_row0_col0\" class=\"data row0 col0\" >100</td>\n      <td id=\"T_d09ba_row0_col1\" class=\"data row0 col1\" >46.970000</td>\n      <td id=\"T_d09ba_row0_col2\" class=\"data row0 col2\" >110.190000</td>\n    </tr>\n  </tbody>\n</table>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n100-year storm intensity at max Tc (46.97 min): 110.19 in/hr\n```\n:::\n:::\n\n\n### Rainfall depth for r.runoff\n\n`r.runoff` takes a total rainfall depth (mm) over the storm duration rather than an intensity rate, so we convert the interpolated intensity back to a depth using the $T_c$-matched storm duration.\n\n::: {#precipitation_mm .cell execution_count=25}\n``` {.python .cell-code}\n# storm_intensity_100yr 46.97 min = 0.7828 hr\nduration_min = 46.97\nintensity_in_hr = 4.34\nintensity_mm_hr = intensity_in_hr * 25.4\n\nduration_hr = duration_min / 60.0\nrain_mm = intensity_mm_hr * duration_hr\n\nprint(f\"Storm duration: {duration_hr:.4f} hr\")\nprint(f\"Rainfall intensity: {intensity_mm_hr:.3f} mm/hr\")\nprint(f\"Rain depth: {rain_mm:.3f} mm\")\ntools.r_mapcalc(\n    expression=f\"rain = {rain_mm}\",  # mm of precipitation\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nStorm duration: 0.7828 hr\nRainfall intensity: 110.236 mm/hr\nRain depth: 86.296 mm\n```\n:::\n:::\n\n\n\n\n::: {#runoff_calculation .cell execution_count=27}\n``` {.python .cell-code}\ntools.r_runoff(\n    rainfall=\"rain\",\n    direction=\"flow_direction\",\n    duration=duration_hr,  # 0.7828 hrs\n    curvenumber=\"curvenumber\",\n    time_concentration=\"time_concentration\",\n    runoff_depth=\"runoff_depth\",\n    runoff_volume=\"runoff_volume\",\n    upstream_area=\"upstream_area\",\n    upstream_runoff_depth=\"upstream_runoff_depth\",\n    upstream_runoff_volume=\"upstream_runoff_volume\",\n    time_to_peak=\"time_to_peak\",\n    peak_discharge=\"peak_discharge\",\n)\n```\n:::\n\n\n### Runoff depth\n\nWith the CN raster, rainfall depth, $T_c$, and flow-direction raster in hand, `r.runoff` produces the full suite of SCS-method outputs: per-cell runoff depth and volume, upstream-accumulated runoff, peak discharge, and time to peak. The `runoff_depth` raster is the critical input to the next step -- once normalized by duration, it becomes the rainfall-excess rate that SIMWE routes across the surface.\n\n::: {#cell-runoff_map .cell layout-ncol='1' execution_count=28}\n\n::: {.cell-output .cell-output-display}\n![Runoff depth (mm) from the SCS method for the $T_c$-matched 100-year storm. Low-CN forest patches shed little runoff; higher-CN valley patches shed several centimeters.](ssurgo_files/figure-html/runoff_map-output-1.png){#runoff_map}\n:::\n:::\n\n\nPeak discharge and time-to-peak maps give complementary information: discharge highlights where flow concentrates, while time-to-peak reveals the temporal response of different sub-basins.\n\n::: {#peak_discharge_map .cell layout-ncol='2' execution_count=29}\n\n::: {.cell-output .cell-output-display}\n![Peak discharge (m³/s)](ssurgo_files/figure-html/peak_discharge_map-output-1.png){#peak_discharge_map-1}\n:::\n\n::: {.cell-output .cell-output-display}\n![Time to peak (hours)](ssurgo_files/figure-html/peak_discharge_map-output-2.png){#peak_discharge_map-2}\n:::\n\nSCS runoff response for the design storm.\n:::\n\n\n## Manning's n Map\n\nSIMWE routes surface flow using the shallow-water momentum equation, with surface friction parameterized by Manning's $n$. Coefficient values depend strongly on land cover: open water has $n \\approx 0.03$, dense forest $n \\approx 0.4$ or higher. `r.manning` assigns $n$ per NLCD class using a lookup table; here we use the values from Kalyanapu et al. (2009), which are calibrated for overland flow rather than channel flow.\n\nInstall `r.manning` if it isn't already available:\n\n::: {#install_manning_extension .cell execution_count=30}\n``` {.python .cell-code}\ntools.g_extension(\n    extension=\"r.manning\"\n)\n```\n:::\n\n\nA fixed `seed=42` keeps the per-class stochastic jitter reproducible across runs.\n\n::: {#cell-r_manning_map .cell execution_count=31}\n``` {.python .cell-code}\ntools.r_manning(\n    input=\"nlcd_2024\",\n    output=\"mannings_n\",\n    landcover=\"nlcd\",\n    source=\"kalyanapu\",\n    seed=42,\n)\n\n\nmannings_n_colors = io.StringIO(\n    \"0.008 #F0E68C\\n\"   # Barren Land (low end)\n    \"0.025 #6BAED6\\n\"   # Open Water\n    \"0.040 #A1D99B\\n\"   # Developed, Open Space / Open Water (med)\n    \"0.068 #BDBDBD\\n\"   # Developed, Low/Med Intensity\n    \"0.160 #F4A460\\n\"   # Cultivated Crops\n    \"0.183 #66C2A4\\n\"   # Emergent Herbaceous Wetlands\n    \"0.325 #D4B86A\\n\"   # Pasture/Hay\n    \"0.368 #A8C25C\\n\"   # Grassland/Herbaceous\n    \"0.400 #2D8C2D\\n\"   # Mixed Forest / Shrub\n    \"0.530 #1A5C1A\\n\"   # Dense Forest (high end)\n)\n\nwith gs.RegionManager(raster=\"mannings_n\", s=\"s-1500\", flags=\"a\"):\n    tools.r_colors(map=\"mannings_n\", rules=mannings_n_colors)\n    m = gj.Map(use_region=True, width=600)\n    m.d_shade(shade=\"relief\", color=\"mannings_n\")\n    m.d_legend(\n        raster=\"mannings_n\",\n        title=\"Manning's n\",\n        at=\"5, 10, 20, 80\",\n        font=\"Fira Sans Condensed Light\",\n        fontsize=16,\n        flags=\"sn\",\n    )\n    # m.d_barscale(\n    #     at=(67, 5),\n    #     font=\"Fira Sans Condensed Light\",\n    #     fontsize=11,\n    #     length=2,\n    #     units=\"kilometers\",\n    #     width_scale=1,\n    #     bgcolor=\"none\",\n    #     color=\"#4f4e4e\",\n    #     flags=\"n\",\n    # )\n    m.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ssurgo_files/figure-html/r_manning_map-output-1.png){#r_manning_map}\n:::\n:::\n\n\n## Run SIMWE\n\nSIMWE (`r.sim.water`) solves the shallow-water momentum equation using a particle-based (walker) approach. Each walker carries a fraction of the total discharge along flow paths computed from the DEM gradient, depth, and Manning's $n$. The model needs four inputs: DEM, slope components ($dx$, $dy$), a rainfall-excess rate (mm/hr), and Manning's $n$. Outputs are per-timestep depth and unit-discharge rasters plus an optional walker vector cloud for visualization.\n\n### Precipitation and Rainfall Excess\n\nThe key difference between soil-aware and naive simulations is the rainfall-excess input. A naive run applies a uniform rate to every cell. The soil-informed version divides the per-cell runoff depth produced by the curve-number analysis by the storm duration, yielding a spatially varying mm/hr rate that implicitly encodes soil infiltration capacity and land-cover abstractions.\n\n| **Location Information** | **Value** |\n|---|---|\n| Name | Otto, North Carolina, USA* |\n| Station name | COWEETA EXP STN |\n| Site ID | 31-2102 |\n| Latitude | 35.0667° |\n| Longitude | -83.4333° |\n| Elevation | 2700 ft** |\n\n![Coweeta Hydrologic Lab](data/coweeta_exp_stn.png)\n\nThe resulting `rainfall_excess` map below is in mm/hr and drives SIMWE's interior source term.\n\n::: {.callout-note}\nThe current divisor of 24 hr is a placeholder for the full daily storm bookkeeping -- the `TODO` in the cell flags that this should be $T_c$-normalized (≈ 0.78 hr) once the runoff model is reconciled with the $T_c$-matched storm duration.\n:::\n\n::: {#cell-rainfall_excess_map .cell execution_count=32}\n``` {.python .cell-code}\n# Time of Concentration: 46.8 min\ntools.r_mapcalc(\n    expression=f\"rainfall_excess = runoff_depth /  0.7828\",  # 0.7828 hr = 46.8 min\n)\n\n\nwith gs.RegionManager(raster=\"rainfall_excess\", s=\"s-1500\", flags=\"a\"):\n    tools.r_colors(map=\"rainfall_excess\", color=\"haxby\", flags=\"en\")\n    m = gj.Map(use_region=True, width=600)\n    m.d_shade(shade=\"relief\", color=\"rainfall_excess\")\n    m.d_legend(\n        raster=\"rainfall_excess\",\n        title=\"Rainfall Excess (mm/hr)\",\n        at=\"5, 10, 20, 80\",\n        font=\"Fira Sans Condensed Light\",\n        fontsize=16,\n        flags=\"n\",\n    )\n    # m.d_barscale(\n    #     at=(67, 5),\n    #     font=\"Fira Sans Condensed Light\",\n    #     fontsize=11,\n    #     length=2,\n    #     units=\"kilometers\",\n    #     width_scale=1,\n    #     bgcolor=\"none\",\n    #     color=\"#4f4e4e\",\n    #     flags=\"n\",\n    # )\n    m.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ssurgo_files/figure-html/rainfall_excess_map-output-1.png){#rainfall_excess_map}\n:::\n:::\n\n\n### Soil-informed simulation\n\nThe first SIMWE run uses the soil-derived `rainfall_excess` map and simulates 48 min (covering the $T_c$-matched 100-year storm) with 100,000 walkers, writing depth, discharge, and walker snapshots every 2 min. The `flags=\"t\"` option emits a time-indexed series rather than summary totals. Outputs are registered into a space-time raster dataset (STRDS) so downstream visualization tools can treat the run as a single animated object.\n\n::: {#r_sim_water .cell execution_count=33}\n``` {.python .cell-code}\n# duration_min = 46.97 round to 47 min for simulation\ntools.r_slope_aspect(elevation=\"elevation\", dx=\"dx\", dy=\"dy\")\ntools.r_sim_water(\n    elevation=\"elevation\",\n    depth=\"tc_100yr_depth\",\n    discharge=\"tc_100yr_discharge\",\n    walkers_output=\"tc_100yr_walkers\",\n    rain=\"rainfall_excess\",  # Infiltration / Veg Intercept\n    man=\"mannings_n\",  # Mixed forest Kalyanapu et al. (2009)\n    nwalkers=100000,\n    # infil=\"ksat_r_sda\", # Infiltration of flowing water\n    # niterations=1440 / 2,\n    observation=\"sample_outlets\",\n    logfile=\"coweeta_100yr_simulation.log\",\n    duration=48, # Bump it to 48 min to cover the full storm duration (rounded up from 46.97 min)\n    output_step=2,\n    nprocs=0,  # auto-detect\n    flags=\"t\",\n)\n\n# Register the output maps into a space time dataset\ngs.run_command(\n    \"t.create\",\n    output=\"tc_100yr_depth_sum\",\n    type=\"strds\",\n    temporaltype=\"absolute\",\n    title=\"Runoff Depth\",\n    description=\"Runoff Depth in [m]\",\n    overwrite=True,\n)\n\n# Get the list of depth maps\ndepth_list = gs.read_command(\n    \"g.list\", type=\"raster\", pattern=\"tc_100yr_depth.*\", separator=\"comma\"\n).strip()\n\n# Register the maps\ngs.run_command(\n    \"t.register\",\n    input=\"tc_100yr_depth_sum\",\n    type=\"raster\",\n    start=\"2024-01-01\",\n    increment=\"2 minutes\",\n    maps=depth_list,\n    flags=\"i\",\n    overwrite=True,\n)\n```\n:::\n\n\n::: {#cell-tc_100yr_depth_map .cell layout-ncol='1' execution_count=34}\n\n::: {.cell-output .cell-output-display}\n![Final-timestep overland flow depth draped over NAIP 2022 imagery. Sample outlet points are marked in orange.](ssurgo_files/figure-html/tc_100yr_depth_map-output-1.png){#tc_100yr_depth_map}\n:::\n:::\n\n\nThe final-timestep depth map above captures the accumulated flood extent once rainfall has routed through the full watershed. To see the temporal evolution -- where water ponds first, which channels fill late, and how the drainage pattern develops -- we render the full STRDS as an animated GIF.\n\n::: {#tc_100_depth_map .cell execution_count=35}\n``` {.python .cell-code}\nwith gs.RegionManager(raster=\"accumulation\", s=\"s-1500\", flags=\"a\"):\n    depth_list = gs.read_command(\n        \"g.list\", type=\"raster\", pattern=\"tc_100yr_depth.*\", separator=\"comma\"\n    ).strip()\n\n    max_depth = depth_list.split(\",\")[-1]\n    stats = tools.r_info(map=max_depth, format=\"json\").json\n    m = gj.TimeSeriesMap(use_region=True, width=700)\n    m.d_rast(map=\"relief\")\n    m.add_raster_series(\"tc_100yr_depth_sum\", values=f\"0.025-{stats['max']}\")\n    m.d_legend(\n        raster=max_depth,\n        title=\"Depth [m]\",\n        flags=\"ls\",\n        border_color=\"none\",\n        range=[0.025, stats[\"max\"]],\n        at=\"5, 10, 20, 80\",\n    )\n\n    m.save(\"output/tc_100yr_simwe_depth_animation.gif\")\n    m.show()\n```\n:::\n\n\n![Animated overland flow depth during the 100-year storm, soil-informed run.](output/tc_100yr_simwe_depth_animation.gif)\n\n### Walker Velocity Animation\n\nThe `walkers_output` from `r.sim.water` stores walker positions but no velocity attribute. SIMWE already emits both depth ($h$) and unit discharge ($q$) per timestep, and by definition $q = h \\cdot v$, so the per-cell flow speed is simply $v = q / h$. Using SIMWE's own outputs keeps the velocity field consistent with the model's internal physics (diffusion wave + Manning + infiltration) rather than re-deriving it from Manning's equation externally. We then sample this velocity raster at each walker position to color the Lagrangian particle cloud.\n\n::: {#compute_velocity_rasters .cell execution_count=36}\n``` {.python .cell-code}\n# Build an STRDS of per-timestep flow-speed rasters directly from SIMWE's own\n# discharge and depth outputs: v = q / h.  This stays self-consistent with the\n# model's internal physics (diffusion-wave + Manning + infiltration) rather\n# than re-deriving velocity from Manning's equation externally.\n\ndepth_list = gs.read_command(\n    \"g.list\", type=\"raster\", pattern=\"tc_100yr_depth.*\", separator=\",\"\n).strip().split(\",\")\n\ndepth_list = [d.split(\"@\", 1)[0] for d in depth_list]\nprint(f\"Found depth maps: {depth_list}\")\n\nvel_list = []\nfor depth in depth_list:\n    suffix = depth.split(\".\", 1)[1]\n    discharge = f\"tc_100yr_discharge.{suffix}\"\n    vel = f\"tc_100yr_velocity.{suffix}\"\n    tools.r_mapcalc(\n        expression=(\n            f\"{vel} = if({depth} > 0.001, {discharge} / {depth}, null())\"\n        ),\n        overwrite=True,\n    )\n    vel_list.append(vel)\n\ngs.run_command(\n    \"t.create\", output=\"tc_100yr_velocity_sum\", type=\"strds\",\n    temporaltype=\"absolute\", title=\"Overland Flow Velocity\",\n    description=\"Flow speed (m/s) from SIMWE discharge / depth\", overwrite=True,\n)\ngs.run_command(\n    \"t.register\", input=\"tc_100yr_velocity_sum\", type=\"raster\",\n    start=\"2024-01-01\", increment=\"2 minutes\",\n    maps=\",\".join(vel_list), flags=\"i\", overwrite=True,\n)\ngs.run_command(\n    \"t.rast.colors\", input=\"tc_100yr_velocity_sum\", color=\"blues\", flags=\"e\",\n)\n```\n:::\n\n\n::: {#walker_stvds .cell execution_count=37}\n``` {.python .cell-code}\n# Subsample walker vectors, attach an attribute table with a velocity column\n# sampled from the v = q/h raster for the matching timestep,\n# store a per-walker color via v.colors, and register an STVDS.\n\n# Walker maps: tc_100yr_walkers_02, _04, ...  Velocity rasters: tc_100yr_velocity.02, .04, ...\nwalker_maps = (\n    gs.read_command(\n        \"g.list\", type=\"vector\", pattern=\"tc_100yr_walkers_*\", separator=\",\"\n    )\n    .strip()\n    .split(\",\")\n)\n# Strip any \"@<mapset>\" qualifier so suffix parsing and the derived output\n# names stay unqualified (same fix as compute_velocity_rasters).\nwalker_maps = [w.split(\"@\", 1)[0] for w in walker_maps]\n\nstep = 50  # keep every Nth walker\n\nsampled = []\nfor wm in walker_maps:\n    suffix = wm.rsplit(\"_\", 1)[1]  # \"02\"\n    print(f\"Processing walker map {wm} with suffix {suffix}\")\n    vel_raster = f\"tc_100yr_velocity.{suffix}\"\n    s = f\"{wm}_sub\"\n\n    # Walker vectors have no attribute table, so `where=` SQL is unavailable.\n    # Get the point count from v.info and pass an explicit cats list instead.\n    vinfo = gs.parse_command(\"v.info\", map=wm, flags=\"t\")\n    n_points = int(vinfo.get(\"points\", 0))\n    cats = \",\".join(str(c) for c in range(1, n_points + 1, step))\n    print(f\"Processing {wm} ({n_points} pts -> {n_points // step} sampled)\")\n\n    gs.run_command(\n        \"v.extract\",\n        input=wm,\n        output=s,\n        cats=cats,\n        overwrite=True,\n    )\n\n    layers = gs.parse_command(\n        \"v.db.connect\", map=s, flags=\"p\", format=\"csv\"\n    )\n\n    if not layers:\n        print(f\"Warning: no attribute table found for {s}, creating one with cats only\")\n        gs.run_command(\n            \"v.db.addtable\",\n            map=s,\n            columns=\"velocity double precision, GRASSRGB varchar(11)\",\n            overwrite=True,\n        )\n    gs.run_command(\n        \"v.what.rast\",\n        map=s,\n        raster=vel_raster,\n        column=\"velocity\",\n    )\n    gs.run_command(\n        \"v.colors\",\n        map=s,\n        use=\"attr\",\n        column=\"velocity\",\n        color=\"blues\",\n        rgb_column=\"GRASSRGB\",\n    )\n    sampled.append(s)\n\ngs.run_command(\n    \"t.create\",\n    output=\"tc_100yr_walkers_stvds\",\n    type=\"stvds\",\n    temporaltype=\"absolute\",\n    title=\"Walker Positions (2% sample)\",\n    description=\"Subsampled Lagrangian walker particles with velocity attribute\",\n    overwrite=True,\n)\n\n# SIMWE uses adaptive timestepping, so the output suffixes aren't on a uniform\n# 2-min grid (e.g. _10, _11, _13). Register with an explicit file of\n# map|start|end rows derived from the suffix so STVDS granularity is well-defined.\nimport tempfile\n\nordered = sorted(sampled, key=lambda s: int(s.split(\"_\")[-2]))\nstarts = [int(s.split(\"_\")[-2]) for s in ordered]\n\nwith tempfile.NamedTemporaryFile(\"w\", suffix=\".txt\", delete=False) as f:\n    for i, s in enumerate(ordered):\n        t_start = starts[i]\n        t_end = starts[i + 1] if i + 1 < len(starts) else t_start + 2\n        start_ts = f\"2024-01-01 {t_start // 60:02d}:{t_start % 60:02d}:00\"\n        end_ts = f\"2024-01-01 {t_end // 60:02d}:{t_end % 60:02d}:00\"\n        f.write(f\"{s}|{start_ts}|{end_ts}\\n\")\n    register_file = f.name\n\ngs.run_command(\n    \"t.register\",\n    input=\"tc_100yr_walkers_stvds\",\n    type=\"vector\",\n    file=register_file,\n    overwrite=True,\n)\ngs.run_command(\"t.support\", input=\"tc_100yr_walkers_stvds\", type=\"stvds\", flags=\"u\")\nprint(gs.read_command(\"t.info\", input=\"tc_100yr_walkers_stvds\", type=\"stvds\"))\n```\n:::\n\n\n::: {#walker_velocity_animation .cell execution_count=38}\n``` {.python .cell-code}\n# Walkers are colored by their per-timestep velocity via the GRASSRGB column.\n# A final-timestep velocity raster is shown only to drive the legend's scale.\nwith gs.RegionManager(raster=\"accumulation\", s=\"s-1500\", flags=\"a\"):\n    vel_list = (\n        gs.read_command(\n            \"g.list\", type=\"raster\", pattern=\"tc_100yr_velocity.*\", separator=\",\"\n        )\n        .strip()\n        .split(\",\")\n    )\n    vmax = tools.r_info(map=vel_list[-1], format=\"json\").json[\"max\"]\n\n    m = gj.TimeSeriesMap(use_region=True, width=700)\n    m.d_shade(shade=\"relief\", color=\"naip_2022_rgb@naip\")\n    m.add_vector_series(\n        \"tc_100yr_walkers_stvds\",\n        rgb_column=\"GRASSRGB\",\n        icon=\"basic/circle\",\n        size=2,\n    )\n    m.d_legend(\n        raster=vel_list[-1],\n        title=\"Velocity (m/s)\",\n        at=\"5, 10, 20, 80\",\n        font=\"Fira Sans Condensed Light\",\n        fontsize=16,\n        range=[0.01, vmax],\n        flags=\"btn\",\n        border_color=\"none\",\n    )\n    # m.d_barscale(\n    #     at=(67, 5),\n    #     font=\"Fira Sans Condensed Light\",\n    #     fontsize=11,\n    #     length=2,\n    #     units=\"kilometers\",\n    #     width_scale=1,\n    #     bgcolor=\"none\",\n    #     color=\"#ffffff\",\n    #     flags=\"n\",\n    # )\n    m.save(\"output/tc_100yr_walker_velocity_animation.gif\")\n    display(m.show())\n```\n:::\n\n\n![Walker positions colored by SIMWE flow speed ($v = q/h$)](output/tc_100yr_walker_velocity_animation.gif)\n\n## Baseline: Uniform Rainfall (No Soil Data)\n\nTo isolate the effect of soil heterogeneity, we run SIMWE a second time with the same DEM, Manning's $n$, and storm intensity, but replace the spatially varying `rainfall_excess` map with a single uniform rate (`rain_value=rain_mm_per_hour`). Any difference between the two runs is attributable solely to the soil-informed rainfall-excess surface rather than changes in terrain or roughness.\n\n::: {#r_sim_water_no_soil .cell execution_count=39}\n``` {.python .cell-code}\ntools.r_sim_water(\n    elevation=\"elevation\",\n    depth=\"no_soil_depth\",\n    discharge=\"no_soil_discharge\",\n    walkers_output=\"no_soil_walkers\",\n    rain_value=rain_mm_per_hour,\n    man=\"mannings_n\",  # Mixed forest Kalyanapu et al. (2009)\n    nwalkers=100000,\n    duration=48, # Bump it to 48 min to cover the full storm duration (rounded up from 46.97 min)\n    observation=\"sample_outlets\",\n    logfile=\"coweeta_100yr_no_soil_simulation.log\",\n    output_step=2,\n    nprocs=0,\n    flags=\"t\",\n)\n\ngs.run_command(\n    \"t.create\",\n    output=\"no_soil_depth_sum\",\n    type=\"strds\",\n    temporaltype=\"absolute\",\n    title=\"Runoff Depth\",\n    description=\"Runoff Depth in [m]\",\n    overwrite=True,\n)\n\n# Get the list of depth maps\ndepth_list = gs.read_command(\n    \"g.list\", type=\"raster\", pattern=\"no_soil_depth.*\", separator=\"comma\"\n).strip()\n\n# Register the maps\ngs.run_command(\n    \"t.register\",\n    input=\"no_soil_depth_sum\",\n    type=\"raster\",\n    start=\"2024-01-01\",\n    increment=\"2 minutes\",\n    maps=depth_list,\n    flags=\"i\",\n    overwrite=True,\n)\n\n```\n:::\n\n\n::: {#1c9ec4c4 .cell execution_count=40}\n``` {.python .cell-code}\nwith gs.RegionManager(raster=\"accumulation\", s=\"s-1500\", flags=\"a\"):\n    m = gj.Map(use_region=True, width=700)\n    stats = tools.r_info(map=\"no_soil_depth.47\", format=\"json\").json\n\n    m.d_shade(shade=\"relief\", color=\"naip_2022_rgb@naip\")\n    m.d_rast(map=\"no_soil_depth.47\", values=f\"0.025-{stats['max']}\")\n    m.d_legend(\n        raster=\"no_soil_depth.47\",\n        title=\"Depth (m)\",\n        at=\"5, 10, 20, 80\",\n        range=[0.025, stats[\"max\"]],\n        font=\"Fira Sans Condensed Light\",\n        fontsize=16,\n        flags=\"ls\",\n        border_color=\"none\",\n    )\n    m.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ssurgo_files/figure-html/cell-41-output-1.png){}\n:::\n:::\n\n\n### Temporal evolution without soils\n\nAnimating the no-soil depth series over the same timeline makes the comparison direct -- watch where, and how quickly, ponded water appears in the uniform-rainfall case versus the soil-informed run above.\n\n::: {#no_soil_depth_map_animation .cell execution_count=41}\n``` {.python .cell-code}\nwith gs.RegionManager(raster=\"accumulation\", s=\"s-1500\", flags=\"a\"):\n    m = gj.TimeSeriesMap(use_region=True, width=700)\n    stats = tools.r_info(map=\"no_soil_depth.47\", format=\"json\").json\n    m.d_rast(map=\"relief\")\n    m.add_raster_series(\"no_soil_depth_sum\", values=f\"0.025-{stats['max']}\")\n    m.d_legend(\n        raster=\"no_soil_depth.47\",\n        title=\"Depth [m]\",\n        flags=\"ls\",\n        range=[0.025, stats[\"max\"]],\n        border_color=\"none\",\n        at=(5, 10, 20, 80),\n    )\n    m.save(\"output/no_soil_simwe_depth_animation.gif\")\n    m.show()\n```\n:::\n\n\n![Animated overland flow depth during the 100-year storm, uniform-rainfall (no-soil) baseline.](output/no_soil_simwe_depth_animation.gif)\n\n",
        "supporting": [
            "ssurgo_files"
        ],
        "filters": [],
        "includes": {
            "include-in-header": [
                "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
            ]
        }
    }
}
