---
title: Scripts
subtitle: Scripts used to generate experimental results.
author: Corey T. White
date: 05/05/2025
date-modified: 05/05/2025
---

* [download_data.py](download_data.py) - script automates the process of downloading, importing, and processing geospatial data using GRASS. It imports elevation data, soil survey data, and NAIP imagery, setting up a GRASS environment for further geospatial analysis.
* [create_figures.py](create_figures.py) - Creates the report figures for each site.
* [create_locations.py](create_locations.py) - Creates a GRASS project for each site from `site-CRS-info.txt`.
* [geomorphology.py](geomorphology.py) - Generates 1st and 2nd order geomorphometric derivatives.
* [groundwater.py](groundwater.py) - Examples of how to seed r.sim.water streams.
* [gutiles.py](gutiles.py) - GRASS utility functions.
* [import_ksat.py](import_ksat.py) - Imports saturated hydraulic conductivity (Ksat) data.
* [sensitivity.py](sensitivity.py) - Runs sensitivity analysis on all of the sites.
* [simulation.py](simulation.py) - Runs the SIMWE simulation on all of the sites.
* [watershed_extent.py](watershed_extent.py) - Explores the sensitivity of r.watershed basin delineation to spatial resolution.
